#!/usr/bin/env python3
"""Build exercise thumbnail coverage reports and frontend static image map.

This script does not generate images. It prepares the exact worklist and keeps
the React Native image map in sync with PNG files that already exist.
"""

from __future__ import annotations

import json
import os
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Set, Tuple

from pymongo import MongoClient


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / "backend" / ".env"
ASSET_DIR = ROOT / "frontend" / "assets" / "images" / "exercise-thumbnails"
DATA_DIR = ROOT / "frontend" / "src" / "data"
OUT_DIR = ROOT / "Research materials" / "legacy" / "thumbnail generation"

COLLECTION_PRIORITY = [
    ("workouts", "active_workout", 0),
    ("primary_exercise_library", "primary", 1),
    ("mobility_drills", "mobility", 2),
    ("exercise_variation_library", "variation", 3),
    ("exercise_library", "source_library", 4),
]


def read_env() -> Tuple[str, str]:
    mongo_url = "mongodb://localhost:27017"
    db_name = "test_database"
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(errors="ignore").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            value = value.strip().strip('"').strip("'")
            if key == "MONGO_URL":
                mongo_url = value
            elif key == "DB_NAME":
                db_name = value
    return mongo_url, db_name


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def exercise_names_from_workout(doc: Dict[str, Any]) -> Iterable[str]:
    plan = doc.get("session_plan") or {}
    for section in ("warmup", "main_work", "cooldown"):
        for exercise in plan.get(section) or []:
            if isinstance(exercise, dict) and exercise.get("name"):
                yield str(exercise["name"])
    for exercise in doc.get("exercises") or []:
        if isinstance(exercise, dict) and exercise.get("name"):
            yield str(exercise["name"])


def collect_names() -> Dict[str, Dict[str, Any]]:
    mongo_url, db_name = read_env()
    client = MongoClient(mongo_url, serverSelectionTimeoutMS=3000)
    client.admin.command("ping")
    db = client[db_name]
    available = set(db.list_collection_names())

    by_slug: Dict[str, Dict[str, Any]] = {}
    for collection_name, tier, priority in COLLECTION_PRIORITY:
        if collection_name not in available:
            continue
        cursor = db[collection_name].find({}, {"name": 1, "title": 1, "session_plan": 1, "exercises": 1})
        for doc in cursor:
            if collection_name == "workouts":
                names = exercise_names_from_workout(doc)
            else:
                name = doc.get("name") or doc.get("title")
                names = [str(name)] if name else []
            for raw_name in names:
                name = raw_name.strip()
                if not name:
                    continue
                slug = slugify(name)
                if not slug:
                    continue
                record = by_slug.setdefault(
                    slug,
                    {
                        "slug": slug,
                        "canonical_name": name,
                        "names": [],
                        "sources": [],
                        "priority": priority,
                    },
                )
                if name not in record["names"]:
                    record["names"].append(name)
                source = {"collection": collection_name, "tier": tier}
                if source not in record["sources"]:
                    record["sources"].append(source)
                if priority < record["priority"]:
                    record["priority"] = priority
                    record["canonical_name"] = name
    return by_slug


def existing_asset_slugs() -> Set[str]:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    return {path.stem for path in ASSET_DIR.glob("*.png")}


def write_frontend_map(asset_slugs: Iterable[str]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "import { ImageSourcePropType } from 'react-native';",
        "",
        "// Generated by backend/exercise_thumbnail_pipeline.py. Do not edit manually.",
        "export const EXERCISE_THUMBNAILS: Record<string, ImageSourcePropType> = {",
    ]
    for slug in sorted(asset_slugs):
        lines.append(
            f"  '{slug}': require('../../assets/images/exercise-thumbnails/{slug}.png'),"
        )
    lines.extend(["};", ""])
    (DATA_DIR / "exerciseThumbnailMap.ts").write_text("\n".join(lines))


def build_batches(missing: List[Dict[str, Any]], batch_size: int = 6) -> List[Dict[str, Any]]:
    batches = []
    for i in range(0, len(missing), batch_size):
        items = missing[i : i + batch_size]
        batches.append(
            {
                "batch_number": len(batches) + 1,
                "items": [{"name": item["canonical_name"], "slug": item["slug"]} for item in items],
                "prompt": make_prompt([item["canonical_name"] for item in items]),
            }
        )
    return batches


def make_prompt(names: List[str]) -> str:
    rows = "six" if len(names) == 6 else str(len(names))
    return (
        "Use case: scientific-educational\n"
        "Asset type: exercise thumbnail contact sheet for a mobile fitness app\n"
        f"Primary request: Create a clean 2 columns by 3 rows grid of {rows} exact exercise movement "
        "thumbnails in this exact row-major order: "
        + ", ".join(names)
        + "."
        + ("\nLeave remaining unused cells as blank white cells with no person." if len(names) < 6 else "")
        + "\nStyle/medium: premium black-and-white fitness instruction illustrations, realistic human anatomy "
        "simplified into clear line art, no cartoon exaggeration.\n"
        "Composition/framing: each used cell shows one full-body person performing the named exercise in the "
        "correct position, centered, isolated, same camera angle consistency, generous padding. White background, "
        "thin light gray cell boundaries.\n"
        "Text: no text, no labels, no logos.\n"
        "Constraints: movements must be technically recognizable and different from each other; use equipment only "
        "when the exercise requires it; no color accents; no watermark."
    )


def write_reports(by_slug: Dict[str, Dict[str, Any]], asset_slugs: Set[str]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    records = sorted(by_slug.values(), key=lambda item: (item["priority"], item["canonical_name"].lower()))
    covered = [item for item in records if item["slug"] in asset_slugs]
    missing = [item for item in records if item["slug"] not in asset_slugs]
    stale_assets = sorted(asset_slugs - set(by_slug))
    batches = build_batches(missing)

    report = {
        "total_required": len(records),
        "covered": len(covered),
        "missing": len(missing),
        "coverage_percent": round((len(covered) / len(records) * 100), 2) if records else 100,
        "stale_assets": stale_assets,
        "records": records,
    }
    (OUT_DIR / "coverage_report.json").write_text(json.dumps(report, indent=2) + "\n")
    (OUT_DIR / "priority_batches.json").write_text(json.dumps(batches, indent=2) + "\n")

    md_lines = [
        "# Exercise Thumbnail Coverage",
        "",
        f"- Required thumbnails: {len(records)}",
        f"- Covered thumbnails: {len(covered)}",
        f"- Missing thumbnails: {len(missing)}",
        f"- Coverage: {report['coverage_percent']}%",
        f"- Stale/unmatched assets: {len(stale_assets)}",
        "",
        "## Missing By Priority",
        "",
    ]
    labels = {0: "active_workout", 1: "primary", 2: "mobility", 3: "variation", 4: "source_library"}
    for priority in range(5):
        items = [item for item in missing if item["priority"] == priority]
        md_lines.append(f"### {labels[priority]} ({len(items)})")
        for item in items[:80]:
            md_lines.append(f"- `{item['slug']}` — {item['canonical_name']}")
        if len(items) > 80:
            md_lines.append(f"- ... {len(items) - 80} more")
        md_lines.append("")
    (OUT_DIR / "coverage_report.md").write_text("\n".join(md_lines))

    prompt_lines = ["# Exercise Thumbnail Generation Batches", ""]
    for batch in batches:
        prompt_lines.append(f"## Batch {batch['batch_number']}")
        prompt_lines.append("")
        prompt_lines.append("```text")
        prompt_lines.append(batch["prompt"])
        prompt_lines.append("```")
        prompt_lines.append("")
    (OUT_DIR / "priority_batch_prompts.md").write_text("\n".join(prompt_lines))


def main() -> None:
    by_slug = collect_names()
    asset_slugs = existing_asset_slugs()
    write_frontend_map(asset_slugs)
    write_reports(by_slug, asset_slugs)
    print(f"required={len(by_slug)} covered={len(asset_slugs & set(by_slug))} missing={len(set(by_slug) - asset_slugs)}")
    print(f"wrote {DATA_DIR / 'exerciseThumbnailMap.ts'}")
    print(f"wrote {OUT_DIR / 'coverage_report.md'}")


if __name__ == "__main__":
    main()
