from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DRAFT_DIR = PROJECT_ROOT / "Research materials" / "legacy" / "exercise research drafts"
NORMALIZED_DIR = DRAFT_DIR / "normalized"


PATTERN_MAP: Dict[str, List[str]] = {
    "bilateral_press": ["horizontal_push"],
    "incline_horizontal_push": ["horizontal_push"],
    "decline_horizontal_push": ["horizontal_push"],
    "incline_horizontal_adduction": ["horizontal_push"],
    "decline_horizontal_adduction": ["horizontal_push"],
    "horizontal_adduction": ["horizontal_push"],
    "chest_accessory": ["horizontal_push"],
    "horizontal_push_accessory": ["horizontal_push"],
    "angled_push": ["horizontal_push"],
    "neutral_grip_press": ["horizontal_push"],
    "reduced_range_press": ["horizontal_push"],
    "unilateral_press": ["horizontal_push", "anti_rotation"],
    "standing_press": ["vertical_push"],
    "rotational_press": ["vertical_push", "rotation_control"],
    "triple_extension_assisted_press": ["vertical_push"],
    "power_press": ["vertical_push"],
    "overhead_arm_position": ["vertical_push"],
    "horizontal_pull": ["horizontal_pull"],
    "unilateral_pull": ["horizontal_pull", "anti_rotation"],
    "supported_row": ["horizontal_pull"],
    "machine_pull": ["horizontal_pull"],
    "seated_pull": ["horizontal_pull"],
    "strict_rowing": ["horizontal_pull"],
    "bodyweight_pull": ["vertical_pull"],
    "assisted_bodyweight_pull": ["vertical_pull"],
    "supinated_pull": ["vertical_pull"],
    "neutral_grip_pull": ["vertical_pull"],
    "vertical_pull_accessory": ["vertical_pull"],
    "vertical_pull_preparation": ["vertical_pull", "scapular_control"],
    "guided_pull": ["vertical_pull"],
    "diagonal_pull": ["vertical_pull"],
    "pullover": ["vertical_pull", "scapular_control"],
    "scapular_retraction": ["scapular_control"],
    "scapular_upward_rotation": ["scapular_control"],
    "scapular_protraction": ["scapular_control"],
    "scapular_depression": ["scapular_control"],
    "external_rotation": ["shoulder_external_rotation"],
    "shoulder_external_rotation": ["shoulder_external_rotation"],
    "shoulder_internal_rotation": ["shoulder_external_rotation"],
    "rear_delt_bias": ["scapular_control"],
    "horizontal_abduction": ["scapular_control"],
    "shoulder_extension": ["scapular_control"],
    "shoulder_flexion": ["vertical_push"],
    "shoulder_abduction": ["vertical_push"],
    "abducted_shoulder_control": ["scapular_control", "shoulder_external_rotation"],
    "elbow_extension": ["horizontal_push"],
    "elbow_extension_strength": ["horizontal_push"],
    "lying_triceps_extension": ["horizontal_push"],
    "elbow_flexion": ["vertical_pull"],
    "unilateral_stabilization": ["anti_rotation"],
    "anti_extension": ["anti_extension"],
    "anti_rotation": ["anti_rotation"],
    "hip_hinge_hold": ["hinge"],
    "eccentric_strength": ["vertical_pull"],
    "dead_stop_pull": ["horizontal_pull"],
    "guided_accessory": ["horizontal_push"],
    "shoulder_extension_position": ["vertical_pull"],
    "neutral_grip": ["vertical_pull"],
    "bilateral_knee_dominant": ["squat"],
    "anterior_loaded": ["squat"],
    "isometric_control": ["squat"],
    "eccentric_control": ["squat"],
    "guided_press": ["squat"],
    "guided_bilateral": ["squat"],
    "bodyweight": ["squat"],
    "isometric": ["anti_extension"],
    "bilateral_pull": ["hinge"],
    "bilateral_hip_dominant": ["hinge"],
    "wide_stance_pull": ["hinge", "adductor"],
    "squat_hinge_hybrid": ["squat", "hinge"],
    "posterior_chain": ["hinge"],
    "long_muscle_length": ["hinge"],
    "axial_loaded": ["squat"],
    "stationary": ["lunge"],
    "rear_foot_elevated": ["lunge"],
    "increased_range": ["lunge"],
    "deep_hip_flexion": ["lunge"],
    "unilateral": ["lunge"],
    "guided_machine": ["squat"],
    "machine": ["squat"],
    "bridge": ["hip_extension"],
    "bent_knee": ["knee_flexion"],
    "plantar_flexion": ["calf_raise"],
    "dorsiflexion": ["ankle_stability"],
    "ankle": ["ankle_stability"],
    "hip_adduction": ["adductor"],
    "frontal_plane": ["adductor"],
    "standing": ["adductor"],
    "side_plank": ["anti_lateral_flexion", "adductor"],
    "locomotion": ["sled_push"],
    "backward_walk": ["sled_pull"],
    "jump": ["hip_extension"],
    "landing": ["lunge"],
    "unilateral_landing": ["lunge"],
    "ballistic_hip_extension": ["hip_extension"],
    "eccentric": ["hinge"],
    "isolation": ["knee_extension"],
    "staggered_stance": ["lunge"],
    "ankle_stability": ["calf_raise"],
    "triple_extension": ["hip_extension"],
    "lateral_locomotion": ["hip_abduction"],
    "hip_dominant_squat": ["squat", "hinge"],
    "increased_range_pull": ["hinge"],
    "hip_hinged": ["calf_raise"],
}


QUALITY_MAP: Dict[str, List[str]] = {
    "upper_body_strength": ["general_strength"],
    "pressing_strength": ["general_strength"],
    "triceps_strength": ["general_strength"],
    "chest_strength": ["general_strength"],
    "shoulder_strength": ["general_strength"],
    "back_strength": ["general_strength"],
    "upper_back_strength": ["general_strength", "scapular_stability"],
    "lat_strength": ["general_strength"],
    "biceps_strength": ["general_strength"],
    "forearm_strength": ["grip_capacity"],
    "grip_strength": ["grip_capacity"],
    "upper_chest_strength": ["general_strength"],
    "posterior_shoulder_strength": ["scapular_stability"],
    "rotator_cuff_strength": ["scapular_stability"],
    "lower_trap_strength": ["scapular_stability"],
    "serratus_strength": ["scapular_stability"],
    "max_strength": ["max_strength"],
    "hypertrophy": ["hypertrophy"],
    "chest_hypertrophy": ["hypertrophy"],
    "upper_chest_hypertrophy": ["hypertrophy"],
    "shoulder_hypertrophy": ["hypertrophy"],
    "back_hypertrophy": ["hypertrophy"],
    "lat_hypertrophy": ["hypertrophy"],
    "upper_back_hypertrophy": ["hypertrophy"],
    "rear_delt_hypertrophy": ["hypertrophy", "scapular_stability"],
    "lateral_delt_hypertrophy": ["hypertrophy"],
    "biceps_hypertrophy": ["hypertrophy"],
    "triceps_hypertrophy": ["hypertrophy"],
    "arm_hypertrophy": ["hypertrophy"],
    "arm_accessory": ["hypertrophy"],
    "machine_accessory": ["hypertrophy"],
    "constant_tension": ["hypertrophy"],
    "time_under_tension": ["hypertrophy"],
    "relative_strength": ["general_strength"],
    "beginner_strength": ["general_strength"],
    "unilateral_strength": ["general_strength", "joint_stability"],
    "accessory_strength": ["general_strength"],
    "strict_rowing": ["general_strength"],
    "lockout_strength": ["general_strength"],
    "upper_body_power": ["power", "rate_of_force_development"],
    "power": ["power"],
    "rate_of_force_development": ["rate_of_force_development"],
    "shoulder_control": ["joint_stability", "scapular_stability"],
    "shoulder_balance": ["joint_stability", "scapular_stability"],
    "shoulder_health": ["joint_stability", "scapular_stability"],
    "shoulder_friendly_pressing": ["joint_stability"],
    "overhead_control": ["joint_stability", "scapular_stability"],
    "overhead_shoulder_control": ["joint_stability", "scapular_stability"],
    "scapular_control": ["scapular_stability"],
    "upper_back_control": ["scapular_stability"],
    "scapular_upward_rotation": ["scapular_stability"],
    "rotator_cuff_support": ["scapular_stability"],
    "rotator_cuff_endurance": ["muscular_endurance", "scapular_stability"],
    "posterior_shoulder_endurance": ["muscular_endurance", "scapular_stability"],
    "serratus_activation": ["scapular_stability"],
    "lower_trap_activation": ["scapular_stability"],
    "closed_chain_shoulder_stability": ["joint_stability", "scapular_stability"],
    "core_control": ["trunk_stiffness"],
    "trunk_stiffness": ["trunk_stiffness"],
    "unilateral_control": ["joint_stability"],
    "movement_control": ["joint_stability"],
    "eccentric_control": ["tissue_capacity"],
    "eccentric_strength": ["tissue_capacity", "general_strength"],
    "pull_up_regression": ["return_to_training"],
    "pulling_regression": ["return_to_training"],
    "chin_up_regression": ["return_to_training"],
    "pull_up_preparation": ["return_to_training", "scapular_stability"],
    "low_back_sparing": ["return_to_training"],
    "rehab_accessory": ["return_to_training"],
    "postural_strength": ["scapular_stability"],
    "warm_up": ["joint_stability"],
    "overhead_mobility": ["joint_stability"],
    "elbow_friendly_pull": ["return_to_training"],
    "load_exposure": ["general_strength"],
    "posterior_chain_isometric": ["trunk_stiffness"],
    "starting_strength": ["power"],
    "pressing_volume": ["hypertrophy", "muscular_endurance"],
    "hip_trunk_integration": ["trunk_stiffness", "joint_stability"],
    "overhead_strength": ["general_strength", "scapular_stability"],
    "lat_isolation": ["hypertrophy"],
    "grip_endurance": ["grip_capacity", "muscular_endurance"],
    "sport_preparation": ["joint_stability"],
    "low_skill_volume": ["hypertrophy"],
    "lower_chest_hypertrophy": ["hypertrophy"],
    "chest_accessory": ["hypertrophy"],
    "rib_control": ["trunk_stiffness"],
    "low_elbow_flexor_demand": ["return_to_training"],
    "elbow_friendly_arm_work": ["return_to_training", "hypertrophy"],
    "long_length_loading": ["hypertrophy"],
    "brachialis_strength": ["general_strength"],
    "long_head_triceps": ["hypertrophy"],
    "elbow_extension_strength": ["general_strength"],
    "pressing_accessory": ["hypertrophy", "general_strength"],
    "posterior_chain": ["posterior_chain_strength"],
    "single_leg_strength": ["single_leg_control", "general_strength"],
    "glute_hypertrophy": ["hypertrophy"],
    "trunk_bracing": ["trunk_stiffness"],
    "pelvic_control": ["hip_control"],
    "quad_strength": ["general_strength"],
    "strength": ["general_strength"],
    "movement_skill": ["joint_stability"],
    "quad_hypertrophy": ["hypertrophy"],
    "stable_loading": ["general_strength"],
    "adductor_strength": ["general_strength", "tissue_capacity"],
    "hamstring_hypertrophy": ["hypertrophy"],
    "balance": ["joint_stability"],
    "hip_stability": ["hip_control", "joint_stability"],
    "mobility": ["joint_stability"],
    "positional_strength": ["general_strength"],
    "bracing": ["trunk_stiffness"],
    "machine_stability": ["general_strength"],
    "low_skill_loading": ["general_strength"],
    "single_leg_stability": ["single_leg_control", "joint_stability"],
    "glute_strength": ["general_strength", "hip_control"],
    "calf_hypertrophy": ["hypertrophy"],
    "ankle_strength": ["ankle_stability", "general_strength"],
    "conditioning": ["conditioning"],
    "landing_mechanics": ["joint_stability", "knee_control"],
    "upright_torso_control": ["trunk_stiffness"],
    "controlled_range": ["joint_stability"],
    "asymmetry_management": ["single_leg_control"],
    "hip_strength": ["general_strength", "hip_control"],
    "unilateral_bias": ["single_leg_control"],
    "hinge_skill": ["joint_stability", "posterior_chain_strength"],
    "low_spinal_loading": ["return_to_training"],
    "foundational_strength": ["general_strength"],
    "dynamic_balance": ["joint_stability"],
    "knee_tracking": ["knee_control"],
    "knee_flexor_strength": ["general_strength", "tissue_capacity"],
    "eccentric_hamstring_strength": ["tissue_capacity", "posterior_chain_strength"],
    "injury_resilience": ["tissue_capacity"],
    "hamstring_strength": ["posterior_chain_strength", "general_strength"],
    "ankle_capacity": ["ankle_stability", "tissue_capacity"],
    "groin_resilience": ["tissue_capacity"],
    "hip_control": ["hip_control"],
    "glute_medius_strength": ["hip_control", "joint_stability"],
    "explosive_power": ["power", "rate_of_force_development"],
    "position_control": ["joint_stability"],
    "depth_access": ["joint_stability"],
    "confidence": ["return_to_training"],
    "technique": ["joint_stability"],
    "trunk_control": ["trunk_stiffness"],
    "reduced_spinal_loading": ["return_to_training"],
    "leg_strength": ["general_strength"],
    "local_strength": ["general_strength"],
    "deceleration": ["knee_control", "single_leg_control"],
    "control": ["joint_stability"],
    "work_capacity": ["muscular_endurance", "conditioning"],
    "lateral_control": ["hip_control", "single_leg_control"],
    "functional_strength": ["general_strength"],
    "lateral_hip_control": ["hip_control", "single_leg_control"],
    "shortened_position_strength": ["general_strength"],
    "motor_control": ["joint_stability"],
    "low_setup_complexity": ["return_to_training"],
    "activation": ["joint_stability"],
    "low_range_complexity": ["return_to_training"],
    "unilateral_glute_strength": ["single_leg_control", "general_strength"],
    "imbalance_management": ["single_leg_control"],
    "progressive_exposure": ["tissue_capacity"],
    "hamstring_endurance": ["muscular_endurance", "posterior_chain_strength"],
    "lower_leg_capacity": ["tissue_capacity", "ankle_stability"],
    "soleus_strength": ["general_strength", "ankle_stability"],
    "calf_strength": ["general_strength", "ankle_stability"],
    "calf_capacity": ["tissue_capacity", "ankle_stability"],
    "shin_strength": ["general_strength", "ankle_stability"],
    "running_accessory": ["tissue_capacity"],
    "lateral_core": ["trunk_stiffness"],
    "trunk_stability": ["trunk_stiffness"],
    "adductor_hypertrophy": ["hypertrophy"],
    "groin_strength": ["general_strength", "tissue_capacity"],
    "adductor_activation": ["joint_stability"],
    "anti_lateral_flexion": ["trunk_stiffness"],
    "groin_capacity": ["tissue_capacity"],
    "pain_monitoring": ["return_to_training"],
    "acceleration_strength": ["power", "general_strength"],
    "leg_drive": ["power"],
    "quad_capacity": ["tissue_capacity"],
    "low_eccentric_stress": ["return_to_training"],
    "reactive_control": ["joint_stability", "power"],
    "single_leg_power": ["power", "single_leg_control"],
    "hip_power": ["power"],
    "glute_medius_activation": ["hip_control", "joint_stability"],
    "warmup": ["joint_stability"],
    "bar_path_control": ["joint_stability"],
    "glute_activation": ["joint_stability"],
    "low_back_capacity": ["tissue_capacity"],
    "stretch_position_loading": ["tissue_capacity"],
    "quad_activation": ["joint_stability"],
    "tendon_capacity": ["tissue_capacity"],
    "knee_tolerance": ["return_to_training", "tissue_capacity"],
}


EQUIPMENT_MAP: Dict[str, List[str]] = {
    "rack": ["squat_rack"],
    "barbell_in_rack": ["barbell", "squat_rack"],
    "incline_bench": ["bench"],
    "decline_bench": ["bench"],
    "flat_bench": ["bench"],
    "bench_optional": ["bench"],
    "bench_or_floor": ["bench"],
    "floor_or_bench": ["bench"],
    "incline_bench_or_handles": ["bench"],
    "bench_blocks_optional": ["bench"],
    "dumbbell": ["dumbbells"],
    "light_dumbbell": ["dumbbells"],
    "light_dumbbells_optional": ["dumbbells"],
    "light_dumbbell_optional": ["dumbbells"],
    "single_handle": ["cable_machine"],
    "handles": ["cable_machine"],
    "handles_optional": ["cable_machine"],
    "row_handle": ["cable_machine"],
    "rope_attachment": ["cable_machine"],
    "rope_or_handles": ["cable_machine"],
    "rope_or_bar_attachment": ["cable_machine"],
    "straight_bar_or_rope": ["cable_machine"],
    "straight_bar": ["cable_machine"],
    "neutral_grip_attachment": ["cable_machine"],
    "pulldown_bar": ["cable_machine"],
    "lat_pulldown_machine": ["machine"],
    "cable_row_machine": ["machine"],
    "row_machine": ["machine"],
    "plate_loaded_row_machine": ["machine"],
    "chest_press_machine": ["machine"],
    "shoulder_press_machine": ["machine"],
    "assisted_pull_up_machine": ["machine"],
    "reverse_pec_deck_machine": ["machine"],
    "pec_deck_machine": ["machine"],
    "pullover_machine": ["machine"],
    "neutral_grip_handles": ["pull_up_bar"],
    "smith_machine_or_rings": ["smith_machine"],
    "landmine_attachment": ["landmine"],
    "ez_bar": ["barbell"],
    "suspension_trainer": ["bodyweight"],
    "box_optional": ["bodyweight"],
    "wall": ["bodyweight"],
    "kettlebells": ["kettlebell"],
    "box": ["bench"],
    "bar_pad": ["barbell"],
    "safety_squat_bar": ["barbell"],
    "heel_wedge": ["plates"],
    "slant_board": ["plates"],
    "belt_squat_machine": ["machine"],
    "dip_belt": ["plates"],
    "hack_squat_machine": ["machine"],
    "pendulum_squat_machine": ["machine"],
    "leg_press_machine": ["machine"],
    "leg_extension_machine": ["machine"],
    "trap_bar": ["barbell"],
    "45_degree_back_extension": ["machine"],
    "plate": ["plates"],
    "hip_thrust_machine": ["machine"],
    "lying_leg_curl_machine": ["machine"],
    "seated_leg_curl_machine": ["machine"],
    "standing_leg_curl_machine": ["machine"],
    "nordic_bench": ["bench"],
    "glute_ham_developer": ["machine"],
    "standing_calf_raise_machine": ["machine"],
    "seated_calf_raise_machine": ["machine"],
    "tibialis_machine": ["machine"],
    "hip_adduction_machine": ["machine"],
    "pad": ["bodyweight"],
    "partner": ["bodyweight"],
    "ankle_cuff": ["cable_machine"],
    "low_platform": ["bench"],
    "ankle_anchor": ["cable_machine"],
    "step": ["bench"],
    "turf": ["sled"],
    "yoga_block": ["bodyweight"],
    "pilates_ball": ["stability_ball"],
    "hip_abduction_machine": ["machine"],
    "strap": ["sled"],
    "plyo_box": ["bench"],
    "mat": ["bodyweight"],
    "reverse_hyper_machine": ["machine"],
    "ankle_strap": ["cable_machine"],
    "sliders": ["bodyweight"],
    "towels": ["bodyweight"],
    "smooth_floor": ["bodyweight"],
    "donkey_calf_machine": ["machine"],
    "belt": ["plates"],
    "thick_resistance_band": ["resistance_band"],
}


MUSCLE_MAP: Dict[str, List[str]] = {
    "pectoralis_major": ["chest"],
    "pectoralis_major_clavicular_head": ["chest"],
    "latissimus_dorsi": ["lats"],
    "teres_major": ["lats"],
    "middle_trapezius": ["mid_back"],
    "lower_trapezius": ["traps"],
    "upper_trapezius": ["traps"],
    "rhomboids": ["upper_back"],
    "posterior_deltoid": ["rear_delts"],
    "anterior_deltoid": ["shoulders"],
    "lateral_deltoid": ["shoulders"],
    "deltoids": ["shoulders"],
    "triceps_brachii": ["triceps"],
    "triceps_brachii_long_head": ["triceps"],
    "triceps_brachii_lateral_head": ["triceps"],
    "triceps_brachii_medial_head": ["triceps"],
    "triceps_long_head": ["triceps"],
    "biceps_brachii": ["biceps"],
    "brachialis": ["biceps"],
    "brachioradialis": ["forearms"],
    "infraspinatus": ["rotator_cuff"],
    "teres_minor": ["rotator_cuff"],
    "subscapularis": ["rotator_cuff"],
    "supraspinatus": ["rotator_cuff"],
    "external_rotators": ["rotator_cuff"],
    "serratus_anterior": ["shoulders"],
    "core": ["trunk"],
    "erector_spinae": ["trunk"],
    "gluteus_maximus": ["glutes"],
    "anconeus": ["triceps"],
    "gluteus_medius": ["glutes"],
    "gluteus_minimus": ["glutes"],
    "gastrocnemius": ["calves"],
    "soleus": ["soleus"],
    "tibialis_anterior": ["tibialis_anterior"],
    "foot_intrinsics": ["tibialis_anterior"],
    "plantaris": ["calves"],
    "hip_flexors": ["quadriceps"],
    "tensor_fasciae_latae": ["glutes"],
    "peroneals": ["calves"],
    "toe_extensors": ["tibialis_anterior"],
    "gracilis": ["adductors"],
    "pectineus": ["adductors"],
    "pelvic_floor": ["deep_core"],
}


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def _unique(items: Iterable[Any]) -> List[Any]:
    result: List[Any] = []
    for item in items:
        if item in (None, "", [], {}):
            continue
        if item not in result:
            result.append(item)
    return result


def _map_list(values: List[str], mapping: Dict[str, List[str]]) -> List[str]:
    mapped: List[str] = []
    for value in values or []:
        mapped.extend(mapping.get(value, [value]))
    return _unique(mapped)


def normalize_record(record: Dict[str, Any]) -> Dict[str, Any]:
    normalized = dict(record)
    normalized["id"] = normalized.get("id") or f"ex_{_slug(str(normalized.get('name') or 'exercise'))}"
    normalized["patterns"] = _map_list(normalized.get("patterns") or [], PATTERN_MAP)
    normalized["qualities"] = _map_list(normalized.get("qualities") or [], QUALITY_MAP)
    normalized["equipment"] = _map_list(normalized.get("equipment") or [], EQUIPMENT_MAP)
    normalized["primary_muscles"] = _map_list(normalized.get("primary_muscles") or [], MUSCLE_MAP)
    normalized["secondary_muscles"] = _map_list(normalized.get("secondary_muscles") or [], MUSCLE_MAP)
    normalized["source_refs"] = [
        ref for ref in normalized.get("source_refs") or []
        if isinstance(ref, dict) and ref.get("title") and ref.get("url")
    ]
    return normalized


def _records(data: Any) -> List[Dict[str, Any]]:
    if isinstance(data, list):
        return [item for item in data if isinstance(item, dict)]
    if isinstance(data, dict):
        for key in ("records", "exercises", "data"):
            if isinstance(data.get(key), list):
                return [item for item in data[key] if isinstance(item, dict)]
    raise ValueError("Draft JSON must be a list or object with records/exercises/data")


def normalize_file(path: Path) -> Path:
    data = json.loads(path.read_text(encoding="utf-8"))
    records = [normalize_record(record) for record in _records(data)]
    NORMALIZED_DIR.mkdir(parents=True, exist_ok=True)
    output_path = NORMALIZED_DIR / path.name
    output_path.write_text(json.dumps(records, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Normalize draft exercise research JSON into canonical taxonomy terms.")
    parser.add_argument("paths", nargs="*", help="Draft JSON paths. Defaults to Research materials/legacy/exercise research drafts/*_draft.json.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    paths = [Path(path) for path in args.paths] or sorted(DRAFT_DIR.glob("*_draft.json"))
    for path in paths:
        output_path = normalize_file(path)
        print(f"{path} -> {output_path}")


if __name__ == "__main__":
    main()
