export type Method = {id:string;code:string;canonical_name:string;method_type:string;movement_pattern:string;status:string;generator_eligible:boolean;content_version:number;technical_cost:number;impact_cost:number;fatigue_cost:number;environments:string[];archived:boolean;identity_version:number};
export type MethodList={items:Method[];next_cursor:string|null;summary:{total:number;generator_eligible:number;needs_completion:number}};
export type MethodEffect={id?:string;quality_code:string;is_primary:boolean;training_role:'preparation'|'primary'|'accessory'|'capacity'|'recovery';magnitude:number;confidence:number;evidence_claim_id:string;evidence_claim_version:number};
export type MethodConstraint={id?:string;constraint_type:string;code:string;condition_json:Record<string,unknown>;action:'exclude'|'modify'|'stop'|'refer'|'require_supervision';athlete_message:string;evidence_claim_id:string|null;evidence_claim_version:number|null};
export type MethodDetail=Method&{effects:MethodEffect[];constraints:MethodConstraint[];relations:Record<string,unknown>[];instructions:string[];cues:string[];common_errors:string[];safety_boundaries:string[];accepted_dose_units:string[];equipment_codes:string[];surfaces:string[];force_directions:string[];contractions:string[];speed_intent:string;level_minimum:string;supervision_required:boolean;record_version:number;method_type:string;movement_pattern:string;joint_positions:Record<string,unknown>;wording_original:boolean;aliases:string[]};
export type EvidenceSource={id:string;title:string;canonical_locator:string;doi:string|null;source_tier:number;publication_year:number|null;population:string|null;context:string|null;limitations:string|null};
export type EvidenceClaim={id:string;code:string;statement:string;claim_type:string;implication_type:string;confidence:number;status:string;claim_version:number};
export type Recipe={id:string;code:string;name:string;recipe_version:number;recipe_type:string;sport_code:string|null;load_class:string;purpose:string;status:string};
export type KnowledgeRelease={id:string;code:string;package_type:string;sport_code:string|null;state:string;release_notes:string;validation_summary:Record<string,unknown>;version:number;content_hash:string|null};
export type ReleaseCandidate={entity_type:string;entity_id:string;entity_version:number;code:string};
export type Simulation={id:string;sport_code:string;scenario_code:string;passed:boolean;result_json:Record<string,unknown>;created_at:string};
export type SourceImport={id:string;source_type:string;source_name:string;status:string;row_count:number;summary_json:Record<string,unknown>;version:number;created_at:string};
export type DatasetStatus={counts:{exercises:number;training_templates:number;training_template_versions:number;sport_priorities:number;category_availability:number;sport_mode_policies:number;mode_fallbacks:number;scenario_overlays:number}};
export type TrainingReference={id:string;code:string;content_version:number;name:string;category_code:string;athlete_level:string;duration_weeks:number;method_count:number;week_count:number;status:string};
export type SportTemplatePriority={id:string;sport_code:string;scope_type:string;scope_code:string;phase_code:string;goal_code:string;primary_template_category:string;session_block_order:string[];priority_basis:string;priorities:{rank:number;category_code:string;weight:number}[];version:number};
export type TrainingPolicies={summary:{total:number;availability:number;sport_modes:number;mode_fallbacks:number;scenario_overlays:number};availability:{id:string;category_code:string;athlete_level:string;available:boolean;template_code:string|null;prerequisite_category:string|null;reason:string;version:number}[];sport_modes:{id:string;sport_code:string;primary_mode:string;cross_training_requires_opt_in:boolean;version:number}[];mode_fallbacks:{id:string;category_code:string;athlete_level:string;requested_mode:string;fallback_category:string;automatic:boolean;version:number}[];scenario_overlays:{id:string;code:string;applies_to:string;instruction:string;version:number}[]};
export type OsmGraph={id:string;version_code:string;source_timestamp:string;status:string;activated_at:string|null;version:number};
export type OsmRegion={id:string;code:string;name:string;pbf_object:string;status:string;version:number;graphs:OsmGraph[]};
export type ModerationFlag={id:string;athlete_id:string;subject_type:string;subject_id:string;flag_code:string;severity:string;status:string;evidence:Record<string,unknown>;created_at:string;version:number};
export type ModerationAppeal={id:string;decision_id:string;athlete_id:string;reason:string;status:string;created_at:string;version:number};
export type OperationsOverview={outbox_unpublished:number;consumer_retries:number;jobs_queued:number;jobs_failed:number;imports_processing:number;imports_failed:number;activities_processing:number;activities_rejected:number;food_processing:number;food_failed:number};
export type OperationsEvent={id:string;topic:string;event_type:string;aggregate_type:string;aggregate_id:string;created_at:string;published_at:string|null;publish_attempts:number;publish_error:string|null;consumer:string|null;consumer_status:string|null;consumer_attempts:number;consumer_error:string|null};
export type RoleUser={id:string;display_name:string;email:string;status:string;roles:string[];version:number};
export type AdminClub={id:string;name:string;slug:string;visibility:string;timezone:string;status:string;member_count:number;created_at:string};
export type AdminClubsResult={summary:{total:number;active:number;archived:number;private:number;pending_requests:number};items:AdminClub[];offset:number;limit:number;has_more:boolean};
export type MethodMedia={id:string;method_id:string;method_version:number;media_type:string;bucket:string;object_name:string;content_hash:string;ownership_status:string;technical_review_status:string;version:number};
export type AdminUser={id:string;display_name:string;email:string;status:string;signed_up_at:string;last_seen_at:string|null;onboarding_completed:boolean;subscription_status:string;plan_code:string|null;subscription_ends_at:string|null};
export type AdminUsersResult={summary:{total:number;subscribed:number;not_subscribed:number};items:AdminUser[];offset:number;limit:number;has_more:boolean};
export type FeatureFlag={id:string;code:string;enabled:boolean;rules:Record<string,unknown>;version:number};
export type AuditRecord={id:string;actor_user_id:string|null;action:string;subject_type:string;subject_id:string|null;before:Record<string,unknown>|null;after:Record<string,unknown>|null;created_at:string};
export type PhysicalQuality={id:string;code:string;name:string;category:string;description:string;status:string;version:number};
export type KnowledgeTerm={id:string;category:string;code:string;name:string;description:string;status:string;version:number};
export type SportTaxon={id:string;code:string;name:string;taxon_type:'sport'|'event'|'role'|'discipline'|'format';sport_code:string;parent_id:string|null;visible:boolean;status:string;version:number};
export type DemandFact={id:string;code:string;fact_version:number;sport_code:string;event_code:string|null;role_code:string|null;discipline_code:string|null;format_code:string|null;weight_class_code:string|null;competition_level:string|null;phase_code:string|null;dimension_code:string;metric_code:string;minimum_value:number|null;maximum_value:number|null;unit:string|null;context:string;implication_type:string;confidence:number;evidence_claim_id:string;evidence_claim_version:number;evidence_claim_code?:string;status:string;record_version:number};
export type QualityPriority={id:string;sport_code:string;event_code:string|null;role_code:string|null;discipline_code:string|null;format_code:string|null;phase_code:string;level_code:string|null;quality_code:string;priority_weight:number;rationale:string;evidence_claim_id:string;evidence_claim_version:number;status:string;version:number};
export type Rule={id:string;code:string;rule_version:number;scope:string;sport_code:string|null;priority:number;conditions_json:Record<string,unknown>;actions_json:Record<string,unknown>[];units_json:Record<string,string>;explanation:string;status:string;record_version:number;evidence_claims?:{id:string;version:number}[]};
export type RecipeSlot={id?:string;slot_code:string;required_quality:string;training_role:string;selection_constraints_json:Record<string,unknown>;dose_schema_json:Record<string,unknown>;required:boolean;sequence?:number;eligible_methods?:{id:string;code:string;name:string;training_role:string}[]};
export type RecipeBlock={id?:string;block_type:string;purpose:string;duration_minimum:number;duration_maximum:number;slots:RecipeSlot[];sequence?:number};
export type RecipeDetail=Recipe&{event_codes:string[];role_codes:string[];discipline_codes:string[];format_codes:string[];phase_codes:string[];goal_codes:string[];level_codes:string[];record_version:number;blocks:RecipeBlock[]};
export type PhaseTemplate={phase_code:string;minimum_weeks:number;maximum_weeks:number;allocation_weight:number;entry_conditions_json:Record<string,unknown>;exit_conditions_json:Record<string,unknown>};
export type Archetype={id:string;code:string;sport_code:string;content_version:number;name:string;event_codes:string[];role_codes:string[];discipline_codes:string[];format_codes:string[];goal_codes:string[];level_codes:string[];minimum_weeks:number;maximum_weeks:number;status:string;record_version:number;phases?:PhaseTemplate[]};
export type WeekTemplate={id:string;code:string;sport_code:string;phase_code:string;level_codes:string[];sessions_minimum:number;sessions_maximum:number;hard_session_maximum:number;spacing_rules_json:Record<string,unknown>;status:string;version:number;recipe_ids:string[]};
export type ContentReview={id:string;entity_type:string;entity_id:string;entity_version:number;review_type:string;decision:string;rationale:string;scope:string;reviewer_user_id:string;decided_at:string};
export type EligibilityReport={total:number;eligible:number;items:{id:string;code:string;content_version:number;eligible:boolean;reasons:string[]}[]};
export type SportCoverage={sport_code:string;counts:Record<string,number>;active_release_id:string|null;coverage_ready:boolean;released:boolean;complete:boolean;missing:string[]};
export type ConflictReport={duplicate_names:{name:string;count:number}[];orphan_recipe_slots:{id:string;quality:string;role:string}[];progression_error:string|null};
export type SourceImportDetail=SourceImport&{rows:{id:string;source_reference:string;normalized_payload:Record<string,unknown>;disposition:string;validation_errors:string[];canonical_method_id:string|null;normalized_name?:string|null;linked_method_id?:string|null;reason?:string|null}[]};

// Local development always uses Vite's same-origin `/api` proxy. This avoids
// stale shell-level VITE_API_URL values bypassing the proxy and pointing the
// browser at an old backend port. Deployed builds still use the configured
// public API origin when one is supplied.
const base = import.meta.env.DEV ? '' : (import.meta.env.VITE_API_URL ?? '');
export const adminRoles=()=>['content_editor','content_publisher','moderator','platform_admin'];
export const canAuthor=()=>adminRoles().some(role=>['content_editor','platform_admin'].includes(role));
export const canPublish=()=>adminRoles().some(role=>['content_publisher','platform_admin'].includes(role));
export const isPlatformAdmin=()=>adminRoles().includes('platform_admin');
export const listAdminUsers=(query='',subscription='all',offset=0,limit=50)=>api<AdminUsersResult>(`/admin/users?query=${encodeURIComponent(query)}&subscription=${encodeURIComponent(subscription)}&offset=${offset}&limit=${limit}`);
export const adminUserDetail=(id:string)=>api<Record<string,unknown>>(`/admin/users/${id}`);
export const updateAdminUserStatus=(id:string,status:string,version:number)=>api(`/admin/users/${id}/status`,{method:'PUT',body:JSON.stringify({status,expected_version:version})});
export const revokeAdminUserSessions=(id:string)=>api(`/admin/users/${id}/revoke-sessions`,{method:'POST'});
export const listAdminClubs=(query='',status='active',offset=0,limit=50)=>api<AdminClubsResult>(`/admin/clubs?query=${encodeURIComponent(query)}&status=${encodeURIComponent(status)}&offset=${offset}&limit=${limit}`);
export const adminClubDetail=(id:string)=>api<Record<string,unknown>>(`/admin/clubs/${id}`);
export const updateAdminClubStatus=(id:string,status:'active'|'archived')=>api(`/admin/clubs/${id}/status`,{method:'PUT',body:JSON.stringify({status})});
export async function api<T>(path:string, init:RequestInit={}):Promise<T>{
  const headers:Record<string,string>={};
  if(!(init.body instanceof FormData)) headers['Content-Type']='application/json';
  Object.assign(headers,init.headers??{});
  if(['POST','PUT','PATCH','DELETE'].includes((init.method??'GET').toUpperCase())&&!headers['Idempotency-Key']) headers['Idempotency-Key']=`admin-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const response=await fetch(`${base}/api/v1${path}`,{...init,headers});
  if(!response.ok){const problem=await response.json().catch(()=>({detail:'Unexpected service error'}));throw new Error(problem.detail??'Request failed');}
  return response.status===204?undefined as T:response.json();
}
export const listMethods=(cursor:string|null=null,query='',signal?:AbortSignal,archived=false)=>api<MethodList>(`/admin/knowledge/methods?limit=250&archived=${archived}${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}${query?`&query=${encodeURIComponent(query)}`:''}`,{signal});
export const createMethod=(body:Record<string,unknown>)=>api<Method>('/admin/knowledge/methods',{method:'POST',body:JSON.stringify(body)});
export const methodDetail=(id:string)=>api<MethodDetail>(`/admin/knowledge/methods/${id}`);
export const updateMethod=(id:string,version:number,body:Record<string,unknown>)=>api<Method>(`/admin/knowledge/methods/${id}/versions/${version}`,{method:'PUT',body:JSON.stringify(body)});
export const createMethodVersion=(id:string)=>api<Method>(`/admin/knowledge/methods/${id}/versions`,{method:'POST'});
export const listMethodVersions=(id:string)=>api<{items:{content_version:number;canonical_name:string;status:string;generator_eligible:boolean;created_at:string;updated_at:string;record_version:number}[]}>(`/admin/knowledge/methods/${id}/versions`).then(x=>x.items);
export const replaceMethodEffects=(id:string,version:number,body:Record<string,unknown>[])=>api(`/admin/knowledge/methods/${id}/versions/${version}/effects`,{method:'PUT',body:JSON.stringify(body)});
export const replaceMethodConstraints=(id:string,version:number,body:Record<string,unknown>[])=>api(`/admin/knowledge/methods/${id}/versions/${version}/constraints`,{method:'PUT',body:JSON.stringify(body)});
export const replaceMethodAliases=(id:string,aliases:string[],version:number)=>api(`/admin/knowledge/methods/${id}/aliases`,{method:'PUT',body:JSON.stringify({aliases,expected_version:version})});
export const archiveMethod=(id:string,archived:boolean,version:number)=>api(`/admin/knowledge/methods/${id}/archive`,{method:'PUT',body:JSON.stringify({archived,expected_version:version})});
export const createMethodRelation=(body:Record<string,unknown>)=>api('/admin/knowledge/relations',{method:'POST',body:JSON.stringify(body)});
export const listMethodMedia=(id:string,version:number)=>api<{items:MethodMedia[]}>(`/admin/knowledge/methods/${id}/versions/${version}/media`).then(x=>x.items);
export const createMethodMedia=(id:string,version:number,body:Record<string,unknown>)=>api<MethodMedia>(`/admin/knowledge/methods/${id}/versions/${version}/media`,{method:'POST',body:JSON.stringify(body)});
export const methodMediaUploadUrl=(id:string,version:number,file:File)=>api<{upload_url:string;bucket:string;object_name:string;media_type:string}>(`/admin/knowledge/methods/${id}/versions/${version}/media/upload-url`,{method:'POST',body:JSON.stringify({file_name:file.name,content_type:file.type})});
export const deleteMethodMedia=(id:string,version:number,mediaId:string)=>api(`/admin/knowledge/methods/${id}/versions/${version}/media/${mediaId}`,{method:'DELETE'});
export const listEvidenceSources=()=>api<{items:EvidenceSource[]}>('/admin/knowledge/evidence/sources').then(x=>x.items);
export const createEvidenceSource=(body:Record<string,unknown>)=>api<EvidenceSource>('/admin/knowledge/evidence/sources',{method:'POST',body:JSON.stringify(body)});
export const listEvidenceClaims=()=>api<{items:EvidenceClaim[]}>('/admin/knowledge/evidence/claims').then(x=>x.items);
export const createEvidenceClaim=(body:Record<string,unknown>)=>api<EvidenceClaim>('/admin/knowledge/evidence/claims',{method:'POST',body:JSON.stringify(body)});
export const evidenceClaimDetail=(id:string)=>api<EvidenceClaim&{source_ids:string[];record_version:number}>(`/admin/knowledge/evidence/claims/${id}`);
export const updateEvidenceClaim=(id:string,version:number,body:Record<string,unknown>)=>api<EvidenceClaim>(`/admin/knowledge/evidence/claims/${id}/versions/${version}`,{method:'PUT',body:JSON.stringify(body)});
export const createEvidenceClaimVersion=(id:string)=>api<EvidenceClaim>(`/admin/knowledge/evidence/claims/${id}/versions`,{method:'POST'});
export const listRecipes=()=>api<{items:Recipe[]}>('/admin/knowledge/session-recipes').then(x=>x.items);
export const createRecipe=(body:Record<string,unknown>)=>api<Recipe>('/admin/knowledge/session-recipes',{method:'POST',body:JSON.stringify(body)});
export const importRecipeCsv=(file:File)=>{const data=new FormData();data.append('file',file);return api<Recipe>('/admin/knowledge/session-recipes/import-csv',{method:'POST',body:data})};
export const recipeDetail=(id:string)=>api<RecipeDetail>(`/admin/knowledge/session-recipes/${id}`);
export const updateRecipe=(id:string,version:number,body:Record<string,unknown>)=>api<RecipeDetail>(`/admin/knowledge/session-recipes/${id}/versions/${version}`,{method:'PUT',body:JSON.stringify(body)});
export const createRecipeVersion=(id:string)=>api<RecipeDetail>(`/admin/knowledge/session-recipes/${id}/versions`,{method:'POST'});
export const listRecipeVersions=(id:string)=>api<{items:{recipe_version:number;name:string;status:string;updated_at:string;record_version:number}[]}>(`/admin/knowledge/session-recipes/${id}/versions`).then(x=>x.items);
export const retireRecipe=(id:string,retired:boolean,version:number)=>api(`/admin/knowledge/session-recipes/${id}/retire`,{method:'PUT',body:JSON.stringify({retired,expected_record_version:version})});
export const listTerms=()=>api<{items:KnowledgeTerm[]}>('/admin/knowledge/terms').then(x=>x.items);
export const createTerm=(body:Record<string,unknown>)=>api<KnowledgeTerm>('/admin/knowledge/terms',{method:'POST',body:JSON.stringify(body)});
export const updateTerm=(id:string,body:Record<string,unknown>)=>api<KnowledgeTerm>(`/admin/knowledge/terms/${id}`,{method:'PUT',body:JSON.stringify(body)});
export const listQualities=()=>api<{items:PhysicalQuality[]}>('/admin/knowledge/qualities').then(x=>x.items);
export const createQuality=(body:Record<string,unknown>)=>api<PhysicalQuality>('/admin/knowledge/qualities',{method:'POST',body:JSON.stringify(body)});
export const updateQuality=(id:string,body:Record<string,unknown>)=>api<PhysicalQuality>(`/admin/knowledge/qualities/${id}`,{method:'PUT',body:JSON.stringify(body)});
export const listSports=()=>api<{items:SportTaxon[]}>('/admin/knowledge/sports').then(x=>x.items);
export const createSportTaxon=(body:Record<string,unknown>)=>api<SportTaxon>('/admin/knowledge/sports',{method:'POST',body:JSON.stringify(body)});
export const updateSportTaxon=(id:string,body:Record<string,unknown>)=>api<SportTaxon>(`/admin/knowledge/sports/${id}`,{method:'PUT',body:JSON.stringify(body)});
export const listDemands=(sport='')=>api<{items:DemandFact[]}>(`/admin/knowledge/demands${sport?`?sport_code=${encodeURIComponent(sport)}`:''}`).then(x=>x.items);
export const createDemand=(body:Record<string,unknown>)=>api<DemandFact>('/admin/knowledge/demands',{method:'POST',body:JSON.stringify(body)});
export const updateDemand=(id:string,version:number,body:Record<string,unknown>)=>api<DemandFact>(`/admin/knowledge/demands/${id}/versions/${version}`,{method:'PUT',body:JSON.stringify(body)});
export const createDemandVersion=(id:string)=>api<DemandFact>(`/admin/knowledge/demands/${id}/versions`,{method:'POST'});
export const listQualityPriorities=(sport='')=>api<{items:QualityPriority[]}>(`/admin/knowledge/quality-priorities${sport?`?sport_code=${encodeURIComponent(sport)}`:''}`).then(x=>x.items);
export const createQualityPriority=(body:Record<string,unknown>)=>api<QualityPriority>('/admin/knowledge/quality-priorities',{method:'POST',body:JSON.stringify(body)});
export const updateQualityPriority=(id:string,body:Record<string,unknown>)=>api<QualityPriority>(`/admin/knowledge/quality-priorities/${id}`,{method:'PUT',body:JSON.stringify(body)});
export const listRules=(sport='')=>api<{items:Rule[]}>(`/admin/knowledge/rules${sport?`?sport_code=${encodeURIComponent(sport)}`:''}`).then(x=>x.items);
export const createRule=(body:Record<string,unknown>)=>api<Rule>('/admin/knowledge/rules',{method:'POST',body:JSON.stringify(body)});
export const ruleDetail=(id:string)=>api<Rule>(`/admin/knowledge/rules/${id}`);
export const validateRule=(body:Record<string,unknown>)=>api<{valid:boolean}>('/admin/knowledge/rules/validate',{method:'POST',body:JSON.stringify(body)});
export const updateRule=(id:string,version:number,body:Record<string,unknown>)=>api<Rule>(`/admin/knowledge/rules/${id}/versions/${version}`,{method:'PUT',body:JSON.stringify(body)});
export const createRuleVersion=(id:string)=>api<Rule>(`/admin/knowledge/rules/${id}/versions`,{method:'POST'});
export const listArchetypes=(sport='')=>api<{items:Archetype[]}>(`/admin/knowledge/program-archetypes${sport?`?sport_code=${encodeURIComponent(sport)}`:''}`).then(x=>x.items);
export const createArchetype=(body:Record<string,unknown>)=>api<Archetype>('/admin/knowledge/program-archetypes',{method:'POST',body:JSON.stringify(body)});
export const archetypeDetail=(id:string)=>api<Archetype>(`/admin/knowledge/program-archetypes/${id}`);
export const updateArchetype=(id:string,version:number,body:Record<string,unknown>)=>api<Archetype>(`/admin/knowledge/program-archetypes/${id}/versions/${version}`,{method:'PUT',body:JSON.stringify(body)});
export const createArchetypeVersion=(id:string)=>api<Archetype>(`/admin/knowledge/program-archetypes/${id}/versions`,{method:'POST'});
export const replaceArchetypePhases=(id:string,version:number,body:PhaseTemplate[])=>api(`/admin/knowledge/program-archetypes/${id}/versions/${version}/phases`,{method:'POST',body:JSON.stringify(body)});
export const listWeeks=(sport='')=>api<{items:WeekTemplate[]}>(`/admin/knowledge/weeks${sport?`?sport_code=${encodeURIComponent(sport)}`:''}`).then(x=>x.items);
export const createWeek=(body:Record<string,unknown>)=>api<WeekTemplate>('/admin/knowledge/weeks',{method:'POST',body:JSON.stringify(body)});
export const updateWeek=(id:string,body:Record<string,unknown>)=>api<WeekTemplate>(`/admin/knowledge/weeks/${id}`,{method:'PUT',body:JSON.stringify(body)});
export const listReviews=(entityType='',decision='')=>api<{items:ContentReview[]}>(`/admin/knowledge/reviews?entity_type=${encodeURIComponent(entityType)}&decision=${encodeURIComponent(decision)}`).then(x=>x.items);
export const createReview=(body:Record<string,unknown>)=>api<ContentReview>('/admin/knowledge/reviews',{method:'POST',body:JSON.stringify(body)});
export const generatorEligibilityReport=()=>api<EligibilityReport>('/admin/knowledge/reports/generator-eligibility');
export const sportCoverageReport=()=>api<{items:SportCoverage[]}>('/admin/knowledge/reports/sport-coverage').then(x=>x.items);
export const conflictReport=()=>api<ConflictReport>('/admin/knowledge/reports/conflicts');
export const listReleases=()=>api<{items:KnowledgeRelease[]}>('/admin/knowledge/releases').then(x=>x.items);
export const createRelease=(body:Record<string,unknown>)=>api<KnowledgeRelease>('/admin/knowledge/releases',{method:'POST',body:JSON.stringify(body)});
export const validateRelease=(id:string)=>api<Record<string,unknown>>(`/admin/knowledge/releases/${id}/validate`,{method:'POST'});
export const releaseCandidates=(id:string)=>api<{items:ReleaseCandidate[]}>(`/admin/knowledge/releases/${id}/candidates`).then(x=>x.items);
export const replaceReleaseManifest=(release:KnowledgeRelease,items:ReleaseCandidate[])=>api<{version:number;item_count:number}>(`/admin/knowledge/releases/${release.id}/manifest`,{method:'PUT',body:JSON.stringify({expected_version:release.version,items})});
export const publishRelease=(release:KnowledgeRelease)=>api(`/admin/knowledge/releases/${release.id}/publish`,{method:'POST',body:JSON.stringify({expected_version:release.version})});
export const rollbackRelease=(release:KnowledgeRelease)=>api(`/admin/knowledge/releases/${release.id}/rollback`,{method:'POST',body:JSON.stringify({expected_version:release.version})});
export const listSimulations=()=>api<{items:Simulation[]}>('/admin/knowledge/simulations').then(x=>x.items);
export const runSimulation=(body:Record<string,unknown>)=>api<Simulation>('/admin/knowledge/simulations',{method:'POST',body:JSON.stringify(body)});
export const listImports=()=>api<{items:SourceImport[]}>('/admin/knowledge/imports').then(x=>x.items);
export const previewExerciseDocument=(file:File)=>{const data=new FormData();data.append('file',file);return api<{id:string;status:string;summary:Record<string,number>;version:number}>('/admin/knowledge/imports',{method:'POST',body:data})};
export const previewWorkbook=previewExerciseDocument;
export const commitWorkbook=(item:SourceImport|{id:string;version:number})=>api(`/admin/knowledge/imports/${item.id}/commit`,{method:'POST',body:JSON.stringify({expected_version:item.version})});
export const previewStructuredDataset=(kind:'training_templates'|'sport_priority_matrix'|'training_policies',files:File[])=>{const data=new FormData();files.forEach(file=>data.append('files',file));return api<{id:string;status:string;row_count:number;summary:Record<string,number>;version:number}>(`/admin/knowledge/dataset-imports/${kind}`,{method:'POST',body:data})};
export const commitStructuredDataset=(item:{id:string;version:number})=>api(`/admin/knowledge/dataset-imports/${item.id}/commit`,{method:'POST',body:JSON.stringify({expected_version:item.version})});
export const getDatasetStatus=()=>api<DatasetStatus>('/admin/knowledge/dataset-status');
export const listTrainingReferences=()=>api<{items:TrainingReference[];total:number}>('/admin/knowledge/training-reference-templates').then(value=>value.items);
export const listSportTemplatePriorities=(sport='')=>api<{items:SportTemplatePriority[];total:number}>(`/admin/knowledge/sport-template-priorities${sport?`?sport_code=${encodeURIComponent(sport)}`:''}`).then(value=>value.items);
export const listTrainingPolicies=(sport='')=>api<TrainingPolicies>(`/admin/knowledge/training-policies${sport?`?sport_code=${encodeURIComponent(sport)}`:''}`);
export const importDetail=(id:string)=>api<SourceImportDetail>(`/admin/knowledge/imports/${id}`);
export const releaseDetail=(id:string)=>api<KnowledgeRelease&{items:ReleaseCandidate[]}>(`/admin/knowledge/releases/${id}`);
export const releaseDiff=(id:string,against?:string)=>api<Record<string,unknown>>(`/admin/knowledge/releases/${id}/diff${against?`?against_release_id=${against}`:''}`);
export const retireRelease=(release:KnowledgeRelease)=>api(`/admin/knowledge/releases/${release.id}/retire`,{method:'POST',body:JSON.stringify({expected_version:release.version})});
export const listOsmRegions=()=>api<{items:OsmRegion[]}>('/admin/osm/regions');
export const createOsmRegion=(body:Record<string,unknown>)=>api('/admin/osm/regions',{method:'POST',body:JSON.stringify(body)});
export const createOsmGraph=(body:Record<string,unknown>)=>api('/admin/osm/graphs',{method:'POST',body:JSON.stringify(body)});
export const markOsmGraphValidating=(id:string,expected_version:number)=>api(`/admin/osm/graphs/${id}/status`,{method:'POST',headers:{'Idempotency-Key':`graph-validating-${id}-${expected_version}`},body:JSON.stringify({status:'validating',expected_version})});
export const activateOsmGraph=(id:string)=>api(`/admin/osm/graphs/${id}/activate`,{method:'POST',headers:{'Idempotency-Key':`graph-activate-${id}`}});
export const listModerationFlags=(status='open')=>api<{items:ModerationFlag[];next_cursor:string|null}>(`/moderation/admin/flags?status=${encodeURIComponent(status)}`);
export const decideModerationFlag=(flag:ModerationFlag,decision:'confirm_violation'|'clear_flag',rationale:string)=>api(`/moderation/admin/flags/${flag.id}/decision`,{method:'POST',headers:{'Idempotency-Key':`flag-${flag.id}-${decision}-${flag.version}`},body:JSON.stringify({decision,rationale,expected_version:flag.version})});
export const listModerationAppeals=(status='open')=>api<{items:ModerationAppeal[];next_cursor:string|null}>(`/moderation/admin/appeals?status=${encodeURIComponent(status)}`);
export const decideModerationAppeal=(appeal:ModerationAppeal,decision:'uphold'|'overturn',rationale:string)=>api(`/moderation/admin/appeals/${appeal.id}/decision`,{method:'POST',headers:{'Idempotency-Key':`appeal-${appeal.id}-${decision}-${appeal.version}`},body:JSON.stringify({decision,rationale,expected_version:appeal.version})});
export const operationsOverview=()=>api<OperationsOverview>('/admin/operations/overview');
export const operationsEvents=()=>api<{items:OperationsEvent[]}>('/admin/operations/events');
export const auditHistory=(action='',subject='')=>api<{items:AuditRecord[]}>(`/admin/operations/audit?action=${encodeURIComponent(action)}&subject_type=${encodeURIComponent(subject)}`).then(x=>x.items);
export const featureFlags=()=>api<{items:FeatureFlag[]}>('/admin/operations/feature-flags').then(x=>x.items);
export const updateFeatureFlag=(body:{code:string;enabled:boolean;rules:Record<string,unknown>;expected_version:number|null})=>api<FeatureFlag>(`/admin/operations/feature-flags/${body.code}`,{method:'PUT',body:JSON.stringify(body)});
export const replayOperationsEvent=(id:string)=>api(`/admin/operations/events/${id}/replay`,{method:'POST',headers:{'Idempotency-Key':`event-replay-${id}-${Date.now()}`}});
export const roleUsers=(query='')=>api<{items:RoleUser[]}>(`/admin/roles/users?query=${encodeURIComponent(query)}`);
export const grantRole=(userId:string,role:string)=>api(`/admin/roles/users/${userId}`,{method:'POST',headers:{'Idempotency-Key':`role-grant-${userId}-${role}`},body:JSON.stringify({role})});
export const revokeRole=(userId:string,role:string)=>api(`/admin/roles/users/${userId}/${role}`,{method:'DELETE',headers:{'Idempotency-Key':`role-revoke-${userId}-${role}-${Date.now()}`}});
export const requestOtp=(email:string)=>api<{challenge_id:string;expires_at:string}>('/auth/otp/request',{method:'POST',body:JSON.stringify({email,purpose:'login'})});
export const verifyOtp=(challenge_id:string,email:string,code:string)=>api<{access_token:string;refresh_token:string;user:{display_name:string;roles:string[]}}>('/auth/otp/verify',{method:'POST',body:JSON.stringify({challenge_id,email,code,device_name:'Runlete Admin Studio'})});
