import { useState } from 'react';
import { Plus, Search, Trash2 } from 'lucide-react';
import { createMethodMedia, deleteMethodMedia, listMethodMedia, methodDetail, type MethodDetail, type MethodMedia } from '../lib/api';
import { ErrorNotice, Header, Modal } from '../components/Studio';

export function Media(){
 const [method,setMethod]=useState<MethodDetail|null>(null),[items,setItems]=useState<MethodMedia[]>([]),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[error,setError]=useState('');async function load(){try{const value=await methodDetail(query.trim());setMethod(value);setItems(await listMethodMedia(value.id,value.content_version))}catch(reason){setError((reason as Error).message)}}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!method)return;const d=new FormData(event.currentTarget);try{await createMethodMedia(method.id,method.content_version,{media_type:d.get('type'),bucket:d.get('bucket'),object_name:d.get('object'),content_hash:d.get('hash'),ownership_status:d.get('ownership'),technical_review_status:d.get('review')});setOpen(false);await load()}catch(reason){setError((reason as Error).message)}}
 async function remove(id:string){if(!method)return;try{await deleteMethodMedia(method.id,method.content_version,id);await load()}catch(reason){setError((reason as Error).message)}}
 return <><Header eyebrow="KNOWLEDGE / METHOD MEDIA" title="Owned and licensed media" description="Only hash-identified Runlete-owned or explicitly licensed objects may be attached to a method version." actions={method&&<button className="primary" onClick={()=>setOpen(true)}><Plus size={16}/>Attach media</button>}/><ErrorNotice message={error}/><section className="panel"><div className="toolbar"><div className="search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Canonical method UUID" onKeyDown={event=>event.key==='Enter'&&void load()}/></div><button className="secondary" onClick={()=>void load()}>Load method</button></div>{method&&<div className="section-heading"><div><h2>{method.canonical_name}</h2><p>{method.code} · version {method.content_version}</p></div></div>}<table><thead><tr><th>OBJECT</th><th>TYPE</th><th>OWNERSHIP</th><th>TECHNICAL REVIEW</th><th>HASH</th><th/></tr></thead><tbody>{items.map(row=><tr key={row.id}><td><strong>{row.object_name}</strong><code>{row.bucket}</code></td><td>{row.media_type}</td><td>{row.ownership_status}</td><td><span className={`status ${row.technical_review_status==='approved'?'ready':'draft'}`}>{row.technical_review_status}</span></td><td><code>{row.content_hash.slice(0,18)}…</code></td><td><button aria-label="Remove media" className="secondary danger" onClick={()=>void remove(row.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></section>{open&&method&&<Modal title="Attach method media" onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={submit}><div className="field-row"><label>Media type<select name="type"><option>image</option><option>video</option><option>animation</option></select></label><label>Ownership<select name="ownership"><option>owned</option><option>licensed</option></select></label><label>Technical review<select name="review"><option>pending</option><option>approved</option><option>rejected</option></select></label></div><label>Cloud Storage bucket<input name="bucket" required/></label><label>Object name<input name="object" required/></label><label>SHA-256 content hash<input name="hash" pattern="[0-9a-f]{64}" required/></label><div className="notice">Uploading the object is a separate signed-upload operation. This record only links an already stored, ownership-verified object.</div><div className="row-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Attach metadata</button></div></form></Modal>}</>;
}
