import { useEffect, useState } from 'react';
import { CheckCircle2, GitCompare, ListChecks, Plus, Rocket, RotateCcw, ShieldOff } from 'lucide-react';
import { canAuthor, canPublish, createRelease, listReleases, publishRelease, releaseCandidates, releaseDetail, releaseDiff, replaceReleaseManifest, retireRelease, rollbackRelease, validateRelease, type KnowledgeRelease, type ReleaseCandidate } from '../lib/api';
import { ErrorNotice, Header, Modal } from '../components/Studio';

const key=(item:ReleaseCandidate)=>`${item.entity_type}:${item.entity_id}:${item.entity_version}`;
export function Releases(){
 const author=canAuthor(),publisher=canPublish();
 const [rows,setRows]=useState<KnowledgeRelease[]>([]),[editing,setEditing]=useState<KnowledgeRelease|null>(null),[candidates,setCandidates]=useState<ReleaseCandidate[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[creating,setCreating]=useState(false),[diff,setDiff]=useState<Record<string,unknown>|null>(null),[error,setError]=useState(''),[working,setWorking]=useState('');const load=()=>listReleases().then(setRows).catch(reason=>setError((reason as Error).message));useEffect(()=>{void load()},[]);
 async function action(id:string,fn:()=>Promise<unknown>){setWorking(id);setError('');try{await fn();await load()}catch(reason){setError((reason as Error).message)}finally{setWorking('')}}
 async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const d=new FormData(event.currentTarget);await action('create',()=>createRelease({code:d.get('code'),package_type:d.get('type'),sport_code:d.get('type')==='sport'?d.get('sport'):null,release_notes:d.get('notes')}));setCreating(false)}
 async function manifest(release:KnowledgeRelease){try{const [available,current]=await Promise.all([releaseCandidates(release.id),releaseDetail(release.id)]);setEditing(release);setCandidates(available);setSelected(new Set(current.items.map(item=>key(item))))}catch(reason){setError((reason as Error).message)}}
 function toggle(item:ReleaseCandidate){const next=new Set(selected),value=key(item);next.has(value)?next.delete(value):next.add(value);setSelected(next)}
 async function save(){if(!editing||!selected.size)return;await action(editing.id,()=>replaceReleaseManifest(editing,candidates.filter(item=>selected.has(key(item)))));setEditing(null)}
 async function compare(row:KnowledgeRelease){try{setDiff(await releaseDiff(row.id))}catch(reason){setError((reason as Error).message)}}
 return <><Header eyebrow="VALIDATION / RELEASE GATE" title="Immutable content releases" description="Publishers activate explicit, validated manifests. Existing athlete plans remain pinned to their original release." actions={author&&<button className="primary" onClick={()=>setCreating(true)}><Plus size={16}/>New release</button>}/><ErrorNotice message={error}/><section className="panel"><table><thead><tr><th>RELEASE</th><th>SPORT</th><th>STATE</th><th>VALIDATION</th><th>PUBLISHED</th><th>ACTIONS</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.code}</strong><code>{row.content_hash?.slice(0,16)||'No content hash'} · v{row.version}</code></td><td>{row.sport_code||'Shared catalogue'}</td><td><span className={`status ${row.state==='released'?'ready':'draft'}`}>{row.state}</span></td><td>{row.validation_summary?.passed===true?<span className="success">Passed</span>:<span className="warn">Not passed</span>}</td><td>{(row as KnowledgeRelease&{published_at?:string}).published_at?new Date((row as KnowledgeRelease&{published_at:string}).published_at).toLocaleString():'—'}</td><td><div className="row-actions"><button title="Compare with previous" className="secondary" onClick={()=>void compare(row)}><GitCompare size={14}/></button>{row.state==='draft'&&<>{author&&<button className="secondary" onClick={()=>void manifest(row)}><ListChecks size={14}/>Manifest</button>}{author&&<button className="secondary" disabled={working===row.id} onClick={()=>void action(row.id,()=>validateRelease(row.id))}><CheckCircle2 size={14}/>Validate</button>}{publisher&&row.validation_summary?.passed===true&&<button className="primary" disabled={working===row.id} onClick={()=>void action(row.id,()=>publishRelease(row))}><Rocket size={14}/>Publish</button>}</>}{publisher&&row.state==='released'&&<button className="secondary danger" disabled={working===row.id} onClick={()=>window.confirm(`Retire ${row.code}? New plans will stop using it.`)&&void action(row.id,()=>retireRelease(row))}><ShieldOff size={14}/>Retire</button>}{publisher&&row.state==='retired'&&<button className="secondary" disabled={working===row.id} onClick={()=>void action(row.id,()=>rollbackRelease(row))}><RotateCcw size={14}/>Rollback</button>}</div></td></tr>)}</tbody></table></section>
 {creating&&<Modal title="Create content release" onClose={()=>setCreating(false)}><form className="form-grid" onSubmit={create}><div className="field-row"><label>Stable release code<input name="code" pattern="[a-z0-9_.-]+" placeholder="running_v1" required/></label><label>Package type<select name="type"><option>sport</option><option>shared</option></select></label><label>Sport code<input name="sport" defaultValue="running"/></label></div><label>Release notes<textarea name="notes" rows={5}/></label><div className="row-actions"><button type="button" className="secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="primary">Create draft</button></div></form></Modal>}
 {editing&&<Modal title={editing.code} eyebrow="EXPLICIT VERSION MANIFEST" onClose={()=>setEditing(null)}><p>Select exact reviewed entity versions. No globally verified content is swept into a release automatically.</p><div className="manifest-tools"><button className="secondary" onClick={()=>setSelected(new Set(candidates.map(key)))}>Select all eligible</button><button className="secondary" onClick={()=>setSelected(new Set())}>Clear</button><strong>{selected.size} selected</strong></div><div className="candidate-list">{candidates.map(item=><label key={key(item)}><input type="checkbox" checked={selected.has(key(item))} onChange={()=>toggle(item)}/><span><strong>{item.code}</strong><small>{item.entity_type} · v{item.entity_version}</small></span></label>)}</div><div className="row-actions"><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={!selected.size||working===editing.id} onClick={()=>void save()}>Replace manifest</button></div></Modal>}
 {diff&&<Modal title="Release difference" eyebrow="IMMUTABLE MANIFEST DIFF" onClose={()=>setDiff(null)}><div className="report-grid">{['added','changed','removed'].map(group=><article key={group}><h2>{group}</h2><pre>{JSON.stringify(diff[group],null,2)}</pre></article>)}</div><div className="row-actions"><button className="secondary" onClick={()=>setDiff(null)}>Close</button></div></Modal>}</>;
}
