import { useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { conflictReport, generatorEligibilityReport, sportCoverageReport, type ConflictReport, type EligibilityReport, type SportCoverage } from '../lib/api';
import { ErrorNotice, Header, Tabs } from '../components/Studio';

export function Reports(){
 const [eligibility,setEligibility]=useState<EligibilityReport|null>(null),[coverage,setCoverage]=useState<SportCoverage[]>([]),[conflicts,setConflicts]=useState<ConflictReport|null>(null),[tab,setTab]=useState('coverage'),[error,setError]=useState('');const load=()=>Promise.all([generatorEligibilityReport(),sportCoverageReport(),conflictReport()]).then(([a,b,c])=>{setEligibility(a);setCoverage(b);setConflicts(c)}).catch(reason=>setError((reason as Error).message));useEffect(()=>{void load()},[]);
 return <><Header eyebrow="VALIDATION / READINESS" title="Knowledge quality reports" description="Publication blockers are visible as concrete missing coverage, ineligible methods, conflicts and orphan references." actions={<button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/>Recalculate</button>}/><ErrorNotice message={error}/><Tabs value={tab} onChange={setTab} items={[{value:'coverage',label:'Sport coverage',count:coverage.length},{value:'methods',label:'Method eligibility',count:eligibility?.total},{value:'conflicts',label:'Conflicts',count:(conflicts?.duplicate_names.length??0)+(conflicts?.orphan_recipe_slots.length??0)+(conflicts?.progression_error?1:0)}]}/><section className="panel">{tab==='coverage'&&<table><thead><tr><th>SPORT</th><th>STATE</th><th>CONTENT COUNTS</th><th>BLOCKERS</th></tr></thead><tbody>{coverage.map(row=><tr key={row.sport_code}><td><strong>{row.sport_code}</strong><code>{row.active_release_id||'No active release'}</code></td><td><span className={`status ${row.complete?'ready':'draft'}`}>{row.complete?'complete':row.coverage_ready?'ready to review':'incomplete'}</span></td><td>{Object.entries(row.counts).map(([key,value])=><span className="metric" key={key}>{key}: {value}</span>)}</td><td><ul className="compact-list">{row.missing.map(item=><li key={item}>{item}</li>)}</ul></td></tr>)}</tbody></table>}{tab==='methods'&&<table><thead><tr><th>METHOD</th><th>VERSION</th><th>ELIGIBLE</th><th>BLOCKERS</th></tr></thead><tbody>{eligibility?.items.map(row=><tr key={row.id}><td><strong>{row.code}</strong><code>{row.id}</code></td><td>{row.content_version}</td><td><span className={`status ${row.eligible?'ready':'draft'}`}>{row.eligible?'yes':'no'}</span></td><td><ul className="compact-list">{row.reasons.map(item=><li key={item}>{item}</li>)}</ul></td></tr>)}</tbody></table>}{tab==='conflicts'&&<div className="report-grid"><article><h2>Duplicate canonical names</h2>{conflicts?.duplicate_names.map(row=><p key={row.name}><strong>{row.name}</strong> appears {row.count} times.</p>)}{!conflicts?.duplicate_names.length&&<p className="success">No duplicate names.</p>}</article><article><h2>Orphan recipe slots</h2>{conflicts?.orphan_recipe_slots.map(row=><p key={row.id}><strong>{row.quality}</strong> / {row.role} has no eligible method effect.</p>)}{!conflicts?.orphan_recipe_slots.length&&<p className="success">No orphan slots.</p>}</article><article><h2>Progression graph</h2>{conflicts?.progression_error?<p className="warn">{conflicts.progression_error}</p>:<p className="success">No progression cycles.</p>}</article></div>}</section></>;
}
