import { useEffect, useState } from 'react';
import { Play, RefreshCw } from 'lucide-react';
import { listSimulations, runSimulation, type Simulation } from '../lib/api';
import { csv, ErrorNotice, Header, Modal } from '../components/Studio';

export function SimulationPage(){
 const [rows,setRows]=useState<Simulation[]>([]),[selected,setSelected]=useState<Simulation|null>(null),[error,setError]=useState(''),[working,setWorking]=useState(false);const load=()=>listSimulations().then(setRows).catch(reason=>setError((reason as Error).message));useEffect(()=>{void load()},[]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const d=new FormData(event.currentTarget);setWorking(true);try{await runSimulation({sport_code:d.get('sport'),scenario_code:d.get('scenario'),release_id:d.get('release')||null,athlete:{level:d.get('level'),available_days:csv(d.get('days')).map(Number),maximum_session_minutes:Number(d.get('minutes')),equipment:csv(d.get('equipment')),environments:csv(d.get('environment')),event_code:d.get('event')||null,role_code:d.get('role')||null,goal_code:d.get('goal')||null}});await load()}catch(reason){setError((reason as Error).message)}finally{setWorking(false)}}
 return <><Header eyebrow="VALIDATION / REPRESENTATIVE ATHLETES" title="Release simulation" description="Resolve every released recipe slot against an athlete’s level, equipment and environment before publication." actions={<button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button>}/><ErrorNotice message={error}/><section className="panel form-panel"><form className="inline-form simulation-form" onSubmit={submit}><label>Sport<input name="sport" defaultValue="running" required/></label><label>Scenario code<input name="scenario" defaultValue="recreational_5k" required/></label><label>Draft/released UUID<input name="release" placeholder="Uses active release if blank"/></label><label>Level<select name="level"><option>beginner</option><option>intermediate</option><option>advanced</option></select></label><label>Event<input name="event" defaultValue="5k"/></label><label>Role<input name="role"/></label><label>Goal<input name="goal" defaultValue="performance"/></label><label>Available weekdays<input name="days" defaultValue="1,3,6"/></label><label>Maximum minutes<input name="minutes" type="number" min="15" max="240" defaultValue="60"/></label><label>Equipment<input name="equipment" defaultValue="bodyweight,band,dumbbell"/></label><label>Environments<input name="environment" defaultValue="road,home"/></label><button className="primary" disabled={working}><Play size={16}/>Run simulation</button></form></section><section className="panel spaced"><table><thead><tr><th>SCENARIO</th><th>SPORT</th><th>RESULT</th><th>SLOT COVERAGE</th><th>EXECUTED</th><th/></tr></thead><tbody>{rows.map(row=>{const result=row.result_json as {resolved_slots?:number;total_slots?:number;errors?:string[]};return <tr className="clickable" onClick={()=>setSelected(row)} key={row.id}><td><strong>{row.scenario_code}</strong><code>{row.id}</code></td><td>{row.sport_code}</td><td><span className={`status ${row.passed?'ready':'draft'}`}>{row.passed?'passed':'failed'}</span></td><td>{result.resolved_slots??0} / {result.total_slots??0}</td><td>{new Date(row.created_at).toLocaleString()}</td><td>{result.errors?.length??0} blockers</td></tr>})}</tbody></table></section>{selected&&<Modal title={selected.scenario_code} eyebrow="SIMULATION RESULT" onClose={()=>setSelected(null)}><pre className="result-json">{JSON.stringify(selected.result_json,null,2)}</pre><div className="row-actions"><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div></Modal>}</>;
}
