import { useEffect, useMemo, useState } from 'react';
import { CircleCheck, Database, FileUp, RefreshCw, Search } from 'lucide-react';
import { commitStructuredDataset, listSportTemplatePriorities, listTrainingPolicies, previewStructuredDataset, type SportTemplatePriority, type TrainingPolicies } from '../lib/api';
import { ErrorNotice, Header, Modal, PageGuide, SuccessNotice } from '../components/Studio';

type View='priorities'|'rules';
type Kind='sport_priority_matrix'|'training_policies';
type Preview={id:string;version:number;row_count:number;summary:Record<string,number>;kind:Kind;label:string;names:string[]};
const sports=['badminton','basketball','boxing','cricket','cycling','football','mma','running','swimming','tennis','volleyball'];
const words=(value:string)=>value.replaceAll('_',' ');
const emptyPolicies:TrainingPolicies={summary:{total:0,sport_modes:0,phase_dose_policies:0},sport_modes:[],phase_dose_policies:[]};

export function SportKnowledge(){
 const [sport,setSport]=useState('running'),[view,setView]=useState<View>('priorities'),[query,setQuery]=useState('');
 const [priorities,setPriorities]=useState<SportTemplatePriority[]>([]),[policies,setPolicies]=useState<TrainingPolicies>(emptyPolicies);
 const [error,setError]=useState(''),[success,setSuccess]=useState(''),[working,setWorking]=useState(false),[preview,setPreview]=useState<Preview|null>(null);
 const filtered=useMemo(()=>priorities.filter(x=>!query||[x.scope_code,x.phase_code,x.goal_code,x.primary_template_category].some(v=>v.toLowerCase().includes(query.toLowerCase()))),[priorities,query]);
 async function load(){setError('');try{const [p,r]=await Promise.all([listSportTemplatePriorities(sport),listTrainingPolicies(sport)]);setPriorities(p);setPolicies(r)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[sport]);
 async function choose(files:File[]){if(!files.length)return;setWorking(true);setError('');try{let kind:Kind,label:string;if(files.length===1&&files[0].name.toLowerCase().endsWith('.csv')){kind='sport_priority_matrix';label='Sport priorities'}else if(files.length===2&&files.every(f=>f.name.toLowerCase().endsWith('.json'))){kind='training_policies';label='Mode and phase policies'}else throw new Error('Select the single 03 priority CSV, or the sport-mode and phase-dose JSON files together.');const result=await previewStructuredDataset(kind,files);if(Number(result.summary.errors||0))throw new Error(`${result.summary.errors} records failed validation.`);setPreview({...result,kind,label,names:files.map(f=>f.name)})}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 async function commit(){if(!preview)return;setWorking(true);try{await commitStructuredDataset(preview);setSuccess(`${preview.label} imported successfully.`);setPreview(null);await load()}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 return <>
  <Header eyebrow="TRAINING" title="Sports & goals" description="Control which training categories matter for each sport, role, phase and goal." actions={<><select value={sport} onChange={e=>setSport(e.target.value)}>{sports.map(x=><option key={x} value={x}>{words(x).replace(/^./,c=>c.toUpperCase())}</option>)}</select><button className="icon-button quiet" onClick={()=>void load()}><RefreshCw size={18}/></button><label className="secondary file-button"><FileUp size={16}/>{working?'Validating…':'Import sport data'}<input hidden multiple type="file" accept=".csv,.json,text/csv,application/json" onChange={e=>{const f=Array.from(e.target.files||[]);e.currentTarget.value='';void choose(f)}}/></label></>}/>
  <PageGuide title="sports and goals" steps={["Sport priorities rank the four-week training categories for each event or role, phase and goal.","Exercise minimum levels and template athlete levels directly control eligibility.","Sport-mode and phase-dose policies are the only separate planning rules.","Upload the 03 CSV for priorities, or both 04 JSON policy files together."]}/>
  <SuccessNotice message={success}/><ErrorNotice message={error}/>
  <section className="stats sport-summary"><div><small>SPORT PRIORITIES</small><strong>{priorities.length}</strong><span>For {sport}</span></div><div><small>SUPPORTING RULES</small><strong>{policies.summary.total}</strong><span>Shared and sport-specific</span></div><div><small>PRIMARY MODE</small><strong className="summary-word">{words(policies.sport_modes[0]?.primary_mode||'Not set')}</strong><span>{sport}</span></div></section>
  <div className="saved-views"><button className={view==='priorities'?'active':''} onClick={()=>setView('priorities')}>Sport priorities <span>{priorities.length}</span></button><button className={view==='rules'?'active':''} onClick={()=>setView('rules')}>Supporting rules <span>{policies.summary.total}</span></button></div>
  <section className="panel resource-index"><div className="section-heading"><div><h2>{view==='priorities'?'Sport priorities':'Supporting planning rules'}</h2><p>{view==='priorities'?'The category rankings used to retrieve relevant four-week templates.':'Primary sport modes and phase-specific dose limits.'}</p></div></div>
   {view==='priorities'&&<div className="index-toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search event, phase, goal or category"/></div></div>}
   <div className="table-scroll">{view==='priorities'?<table><thead><tr><th>SCOPE</th><th>PHASE</th><th>GOAL</th><th>PRIMARY CATEGORY</th><th>RANKED SUPPORT</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{words(x.scope_code)}</strong><code>{x.scope_type}</code></td><td>{words(x.phase_code)}</td><td>{words(x.goal_code)}</td><td>{words(x.primary_template_category)}</td><td>{x.priorities.slice(0,4).map(p=>`${p.rank}. ${words(p.category_code)}`).join(' · ')}</td></tr>)}{!filtered.length&&<tr><td colSpan={5} className="table-empty">No priorities found.</td></tr>}</tbody></table>
   :<table><thead><tr><th>RULE TYPE</th><th>SCOPE</th><th>BEHAVIOUR</th><th>DETAIL</th></tr></thead><tbody>{policies.sport_modes.map(x=><tr key={x.id}><td>Sport mode</td><td><strong>{words(x.sport_code)}</strong></td><td>{words(x.primary_mode)}</td><td>{x.cross_training_requires_opt_in?'Cross-training requires athlete opt-in':'Cross-training allowed'}</td></tr>)}{policies.phase_dose_policies.map(x=><tr key={x.id}><td>Phase dose</td><td>{words(x.phase_code)}</td><td>{words(x.progression_mode)} · max {x.maximum_sessions_per_week}/week</td><td>{words(x.novelty_policy)}</td></tr>)}</tbody></table>}</div>
  </section>
  {preview&&<Modal title="Review sport data import" onClose={()=>!working&&setPreview(null)}><div className="import-verdict"><CircleCheck size={22}/><div><strong>Validation passed</strong><span>All records are ready to commit.</span></div></div><div className="user-detail import-summary"><article><Database size={18}/><small>DATASET</small><strong>{preview.label}</strong></article><article><small>VALID RECORDS</small><strong>{preview.row_count}</strong></article><article><small>FILES</small><strong>{preview.names.length}</strong></article></div><div className="import-files">{preview.names.map(n=><div key={n}><FileUp size={14}/><span>{n}</span></div>)}</div><div className="row-actions modal-actions"><button className="secondary" onClick={()=>setPreview(null)}>Cancel</button><button className="primary" disabled={working} onClick={()=>void commit()}>{working?'Importing…':'Commit to PostgreSQL'}</button></div></Modal>}
 </>;
}
