import { useEffect, useState } from 'react';
import { BookOpen, Edit3, ExternalLink, Plus, RefreshCw, Rocket } from 'lucide-react';
import { createSportContentArticle, createSportContentSource, createSportContentVersion, listSportContent, listSportContentSources, publishSportContent, saveSportContentVersion, sportContentDetail, updateSportContentSource, type SportContentArticle, type SportContentArticleDetail, type SportContentSource } from '../lib/api';
import { ErrorNotice, Header, Modal, PageGuide, SuccessNotice, Tabs } from '../components/Studio';

const disclaimer='Educational information only. It does not diagnose injury or replace a qualified clinician or coach. Stop exercise and seek urgent help for chest pain, fainting, severe breathing difficulty, confusion, collapse, major trauma, or signs of heat stroke.';
const sports=['badminton','basketball','boxing','cricket','cycling','football','mma','running','swimming','tennis','volleyball'];

export function SportContent(){
 const [items,setItems]=useState<SportContentArticle[]>([]),[editing,setEditing]=useState<SportContentArticleDetail|null>(null);
 const [sources,setSources]=useState<SportContentSource[]>([]),[editingSource,setEditingSource]=useState<SportContentSource|null>(null),[tab,setTab]=useState('articles');
 const [sport,setSport]=useState('running'),[newArticle,setNewArticle]=useState<{title:string;slug:string;category:string}|null>(null),[newSource,setNewSource]=useState<{source_key:string;title:string;canonical_url:string;publication_year:number;source_kind:string}|null>(null);
 const [sections,setSections]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[working,setWorking]=useState(false);
 async function load(){setError('');try{const [articles,evidence]=await Promise.all([listSportContent(sport),listSportContentSources()]);setItems(articles);setSources(evidence)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[sport]);
 async function open(item:SportContentArticle){setWorking(true);try{let detail=await sportContentDetail(item.id);if(detail.status!=='draft'){await createSportContentVersion(item.id);detail=await sportContentDetail(item.id)}setEditing(detail);setSections(JSON.stringify(detail.sections,null,2))}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 async function save(){if(!editing)return;setWorking(true);try{const parsed=JSON.parse(sections);const value=await saveSportContentVersion(editing,{title:editing.title,category:editing.category,summary:editing.summary,icon:editing.icon,audiences:editing.audiences,events:editing.events,sections:parsed,medical_disclaimer:editing.medical_disclaimer,reviewed_on:editing.reviewed_on,source_ids:editing.source_ids});setEditing(value);setSuccess('Draft saved. Published users still see the previous release.');await load()}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 async function publish(){setWorking(true);try{const result=await publishSportContent(sport,{title:sport[0].toUpperCase()+sport.slice(1),subtitle:`Evidence-informed ${sport} skills, training and competition knowledge`,medical_disclaimer:disclaimer});setSuccess(`Published ${sport} release ${String(result.release_version)}.`);await load()}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 async function saveSource(){if(!editingSource)return;setWorking(true);try{const value=await updateSportContentSource(editingSource,{title:editingSource.title,canonical_url:editingSource.canonical_url,publication_year:editingSource.publication_year,source_kind:editingSource.source_kind,editorial_note:editingSource.editorial_note});setEditingSource(value);setSuccess('Evidence source updated.');await load()}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 async function addArticle(){if(!newArticle)return;setWorking(true);try{const value=await createSportContentArticle({...newArticle,sport_code:sport});setNewArticle(null);setSuccess(`Draft article “${value.title}” created.`);await load();await open(value)}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 async function addSource(){if(!newSource)return;setWorking(true);try{await createSportContentSource({...newSource,editorial_note:''});setNewSource(null);setSuccess('Evidence source created.');await load()}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 return <>
  <Header eyebrow="ATHLETE EDUCATION" title="Sport articles" description="Edit evidence-linked content stored in PostgreSQL." actions={<><select aria-label="Sport" value={sport} onChange={e=>setSport(e.target.value)}>{sports.map(value=><option value={value} key={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select><button className="icon-button quiet" onClick={()=>void load()}><RefreshCw size={18}/></button><button className="secondary" disabled={working} onClick={()=>setNewArticle({title:'',slug:'',category:'foundations'})}><Plus size={16}/>New article</button><button className="primary" disabled={working||!items.length} onClick={()=>void publish()}><Rocket size={16}/>Publish {sport}</button></>}/>
  <PageGuide title="sport articles" steps={["Seed imports the reviewed JSON only when Running has no published database content.","Edit creates a new draft, leaving the mobile release untouched.","Publish validates every article and atomically creates a new PostgreSQL release."]}/>
  <SuccessNotice message={success}/><ErrorNotice message={error}/>
  <section className="stats"><div><small>{sport.toUpperCase()} ARTICLES</small><strong>{items.length}</strong><span>Database records</span></div><div><small>EVIDENCE SOURCES</small><strong>{sources.length}</strong><span>Shared editable citations</span></div><div><small>DRAFTS</small><strong>{items.filter(x=>x.status==='draft').length}</strong><span>Not yet mobile-visible</span></div></section>
  <Tabs value={tab} onChange={setTab} items={[{value:'articles',label:'Articles',count:items.length},{value:'sources',label:'Evidence sources',count:sources.length}]}/>
  {tab==='articles'?<section className="panel resource-index"><div className="section-heading"><div><h2>{sport[0].toUpperCase()+sport.slice(1)} knowledge</h2><p>Stable articles with immutable versions and evidence links.</p></div></div><div className="table-scroll"><table><thead><tr><th>ARTICLE</th><th>CATEGORY</th><th>VERSION</th><th>STATUS</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.title}</strong><code>{item.slug}</code><p>{item.summary}</p></td><td>{item.category}</td><td>v{item.latest_version} · live {item.published_version??'—'}</td><td>{item.status}</td><td><button className="icon-button quiet" disabled={working} onClick={()=>void open(item)}><Edit3 size={16}/></button></td></tr>)}{!items.length&&<tr><td colSpan={5} className="table-empty"><BookOpen size={20}/>No content yet. Create the first draft article.</td></tr>}</tbody></table></div></section>:
  <section className="panel resource-index"><div className="section-heading"><div><h2>Evidence library</h2><p>Canonical citations shared by sport articles. Source keys remain stable when metadata changes.</p></div><button className="secondary" onClick={()=>setNewSource({source_key:'',title:'',canonical_url:'',publication_year:new Date().getFullYear(),source_kind:'guideline'})}><Plus size={16}/>New source</button></div><div className="table-scroll"><table><thead><tr><th>SOURCE</th><th>YEAR</th><th>TYPE</th><th>LINK</th><th></th></tr></thead><tbody>{sources.map(source=><tr key={source.id}><td><strong>{source.title}</strong><code>{source.source_key}</code><p>{source.editorial_note}</p></td><td>{source.publication_year}</td><td>{source.source_kind}</td><td><a href={source.canonical_url} target="_blank" rel="noreferrer" aria-label={`Open ${source.title}`}><ExternalLink size={16}/></a></td><td><button className="icon-button quiet" disabled={working} onClick={()=>setEditingSource(source)}><Edit3 size={16}/></button></td></tr>)}</tbody></table></div></section>}
  {editing&&<Modal title={`Edit ${editing.title} · v${editing.content_version}`} onClose={()=>!working&&setEditing(null)}><div className="form-grid"><label>Title<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Category<input value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/></label><label className="full">Summary<textarea rows={3} value={editing.summary} onChange={e=>setEditing({...editing,summary:e.target.value})}/></label><label className="full">Sections (validated JSON)<textarea rows={18} spellCheck={false} value={sections} onChange={e=>setSections(e.target.value)}/></label><label className="full">Evidence source IDs<input value={editing.source_ids.join(', ')} onChange={e=>setEditing({...editing,source_ids:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label className="full">Safety boundary<textarea rows={4} value={editing.medical_disclaimer} onChange={e=>setEditing({...editing,medical_disclaimer:e.target.value})}/></label></div><div className="row-actions modal-actions"><button className="secondary" onClick={()=>setEditing(null)}>Close</button><button className="primary" disabled={working} onClick={()=>void save()}>{working?'Saving…':'Save draft'}</button></div></Modal>}
  {editingSource&&<Modal title={`Edit source · ${editingSource.source_key}`} eyebrow="EVIDENCE LIBRARY" onClose={()=>!working&&setEditingSource(null)}><div className="form-grid"><label className="full">Title<input value={editingSource.title} onChange={e=>setEditingSource({...editingSource,title:e.target.value})}/></label><label>Publication year<input type="number" value={editingSource.publication_year} onChange={e=>setEditingSource({...editingSource,publication_year:Number(e.target.value)})}/></label><label>Source type<input value={editingSource.source_kind} onChange={e=>setEditingSource({...editingSource,source_kind:e.target.value})}/></label><label className="full">Canonical URL<input type="url" value={editingSource.canonical_url} onChange={e=>setEditingSource({...editingSource,canonical_url:e.target.value})}/></label><label className="full">Editorial note<textarea rows={4} value={editingSource.editorial_note} onChange={e=>setEditingSource({...editingSource,editorial_note:e.target.value})}/></label></div><div className="row-actions modal-actions"><button className="secondary" onClick={()=>setEditingSource(null)}>Close</button><button className="primary" disabled={working} onClick={()=>void saveSource()}>{working?'Saving…':'Save source'}</button></div></Modal>}
  {newArticle&&<Modal title={`New ${sport} article`} onClose={()=>!working&&setNewArticle(null)}><div className="form-grid"><label className="full">Title<input value={newArticle.title} onChange={e=>setNewArticle({...newArticle,title:e.target.value})}/></label><label>Slug<input placeholder="lowercase-hyphenated" value={newArticle.slug} onChange={e=>setNewArticle({...newArticle,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})}/></label><label>Category<input value={newArticle.category} onChange={e=>setNewArticle({...newArticle,category:e.target.value})}/></label></div><div className="row-actions modal-actions"><button className="secondary" onClick={()=>setNewArticle(null)}>Cancel</button><button className="primary" disabled={working||!newArticle.title||!newArticle.slug} onClick={()=>void addArticle()}>Create draft</button></div></Modal>}
  {newSource&&<Modal title="New evidence source" eyebrow="EVIDENCE LIBRARY" onClose={()=>!working&&setNewSource(null)}><div className="form-grid"><label>Stable source key<input value={newSource.source_key} onChange={e=>setNewSource({...newSource,source_key:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})}/></label><label>Publication year<input type="number" value={newSource.publication_year} onChange={e=>setNewSource({...newSource,publication_year:Number(e.target.value)})}/></label><label className="full">Title<input value={newSource.title} onChange={e=>setNewSource({...newSource,title:e.target.value})}/></label><label>Source type<input value={newSource.source_kind} onChange={e=>setNewSource({...newSource,source_kind:e.target.value})}/></label><label className="full">Canonical URL<input type="url" value={newSource.canonical_url} onChange={e=>setNewSource({...newSource,canonical_url:e.target.value})}/></label></div><div className="row-actions modal-actions"><button className="secondary" onClick={()=>setNewSource(null)}>Cancel</button><button className="primary" disabled={working||!newSource.source_key||!newSource.title||!newSource.canonical_url} onClick={()=>void addSource()}>Create source</button></div></Modal>}
 </>;
}
