#!/usr/bin/env python3
"""Append the 58 template-required methods to Runlete's curated CSV.

Idempotent: previously generated EXT- rows are replaced, while all existing
curated rows and their order are preserved.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "Backend data files" / "exercises" / "curated_exercises.csv"
FIELDS = [
    "source_id", "exercise_name", "code", "aliases", "type", "movement_pattern",
    "primary_quality", "secondary_qualities", "training_role", "primary_muscles",
    "secondary_muscles", "equipment", "environments", "minimum_level",
    "technical_cost", "impact_cost", "fatigue_cost", "supervision_required",
    "dose_units", "instructions", "coaching_cues", "common_mistakes",
    "safety_stop_conditions", "progressions", "regressions", "substitutions",
    "catalogue_scope", "generator_eligible", "approval_status", "approved_by",
    "approval_scope",
]


def E(code, name, kind, pattern, primary, secondary, role, muscles, equipment,
      environments, level, costs, supervision, dose, instructions, cues, mistakes,
      safety, progressions, regressions, substitutions, aliases=""):
    method_type = {
        "landing_drill": "athletic_drill",
        "speed_drill": "athletic_drill",
        "deceleration_drill": "athletic_drill",
        "change_of_direction_drill": "athletic_drill",
        "reactive_agility_drill": "athletic_drill",
        "isometric": "exercise",
        "recovery_modality": "conditioning_modality",
    }.get(kind, kind)
    return dict(code=code, exercise_name=name, aliases=aliases, type=method_type,
                movement_pattern=pattern, primary_quality=primary,
                secondary_qualities=secondary, training_role=role,
                primary_muscles=muscles, secondary_muscles="trunk;supporting musculature",
                equipment=equipment, environments=environments, minimum_level=level,
                technical_cost=str(costs[0]), impact_cost=str(costs[1]),
                fatigue_cost=str(costs[2]), supervision_required=supervision,
                dose_units=dose, instructions=instructions, coaching_cues=cues,
                common_mistakes=mistakes, safety_stop_conditions=safety,
                progressions=progressions, regressions=regressions,
                substitutions=substitutions)


SPEED_DOSE = "sets;repetitions;distance_m;intensity_percent;recovery_seconds"
LAND_DOSE = "sets;repetitions;contacts;effort_rpe;recovery_seconds"
COD_DOSE = "sets;repetitions;distance_m;approach_intensity_percent;cut_angle_degrees;recovery_seconds"
ISO_DOSE = "sets;duration_seconds;effort_rpe;joint_position;recovery_seconds"
COND_DOSE = "sets;repetitions;duration_seconds;distance_m;intensity_system;recovery_seconds;set_recovery_seconds"
REC_DOSE = "duration_seconds;effort_rpe;intensity_system"
STOP = "Stop for pain, dizziness, chest pain, unusual breathlessness, neurological symptoms, loss of balance, acute illness, unsafe conditions, or clear loss of controlled technique."
SPEED_STOP = STOP + " End high-speed work when speed or mechanics clearly deteriorate; use a safe unobstructed surface and adequate recovery."
COND_STOP = STOP + " End the interval set when output falls beyond the prescribed limit or the athlete cannot maintain the intended intensity domain."


ENTRIES = [
    E("easy_mode_specific_raise","Easy Mode-Specific Raise","preparation_drill","cyclical_locomotion","mobility_preparation","recovery_capacity","preparation","whole_body","mode_specific","field;gym;home;road;track;court;pool","beginner",(1,1,1),"no","duration_seconds;effort_rpe","Perform easy movement matching or supporting the coming session, gradually raising temperature without creating fatigue.","Easy rhythm. Breathe comfortably. Finish warmer, not tired.","Starting too hard. Turning the raise into conditioning. Using a mode that aggravates symptoms.",STOP,"Longer or more task-specific raise within the warm-up time budget","Shorter walk or gentle cycle","walking;easy cycling;easy swimming"),
    E("snap_down","Snap-Down","landing_drill","bilateral_landing","landing_capacity","deceleration;trunk_force_transfer","preparation","quadriceps;glutes;calves","","field;gym;court;home","beginner",(2,1,1),"no",LAND_DOSE,"Rise tall, then rapidly lower into an athletic landing position and hold it under control.","Land quietly. Whole foot. Hips and knees share the stop.","Knees collapsing. Heels lifting. Chest folding. Failing to hold the finish.",STOP,"Bilateral jump and stick; directional jump to stick","Slower squat-to-stick","bodyweight squat to controlled stop"),
    E("bilateral_jump_to_stick","Bilateral Jump and Stick","landing_drill","bilateral_jump_landing","landing_capacity","vertical_power;deceleration","primary","quadriceps;glutes;calves","soft_landing_surface","field;gym;court;home","beginner",(2,2,2),"no",LAND_DOSE,"Jump vertically or slightly forward from two feet, land on two feet and hold the landing before resetting.","Quiet contact. Knees track. Freeze the landing.","Chasing height before control. Rebounding immediately. Stiff or asymmetric landing.",STOP,"Drop landing to stick; directional jump to stick","Snap-down; lower jump","standing jump-and-reach with submaximal height"),
    E("drop_landing_to_stick","Drop Landing to Stick","landing_drill","bilateral_drop_landing","landing_capacity","deceleration;eccentric_capacity","primary","quadriceps;glutes;calves","low_box;soft_landing_surface","field;gym;court","intermediate",(3,3,2),"yes",LAND_DOSE,"Step—not jump—off a reviewed low box, land on two feet and stabilize before leaving the position.","Step off. Meet the floor. Hold the finish.","Jumping upward from the box. Excessive height. Collapsing or bouncing out of the landing.",STOP + " Box height must be reviewed and must not increase unless repeated landing quality remains acceptable.","Higher but reviewed drop; single-leg land and stick","Bilateral jump and stick; snap-down","directional jump to stick"),
    E("single_leg_land_and_stick","Single-Leg Land and Stick","landing_drill","unilateral_landing","landing_capacity","deceleration;single_leg_control","primary","quadriceps;glutes;calves","soft_landing_surface","field;gym;court","intermediate",(3,3,3),"yes",LAND_DOSE,"Use a small hop or step-off, land on one leg and hold alignment without the free foot touching down.","Own the landing. Hip, knee and foot aligned. Hold before resetting.","Too much displacement. Pelvis dropping. Knee collapsing. Reaching the free foot down immediately.",STOP,"Greater displacement or directional entry; repeated unilateral hop","Supported step-down; bilateral jump and stick","single-leg lateral jump to stick"),
    E("wall_march","Wall March","speed_drill","acceleration_posture","acceleration","mobility_preparation;trunk_force_transfer","preparation","hip_flexors;glutes;calves","wall","field;gym;home;track;court","beginner",(2,1,1),"no",SPEED_DOSE,"Lean into a wall with a straight body line. Alternate controlled march positions while keeping the stance leg long and foot active.","Push the wall away. Ribcage and pelvis stacked. Switch without losing posture.","Bending at the waist. Reaching the foot forward. Collapsing through the ankle.",STOP,"Wall switch; falling-start acceleration","Static wall hold; slower march","A-march"),
    E("wall_switch","Wall Switch","speed_drill","acceleration_posture","acceleration","explosive_strength;trunk_force_transfer","preparation","hip_flexors;glutes;calves","wall","field;gym;home;track;court","intermediate",(3,1,2),"no",SPEED_DOSE,"From a wall acceleration position, rapidly exchange the thigh positions and regain a stable posture after each switch.","Strike and hold. Keep the body line. Fast exchange, stable finish.","Cycling the legs. Hips dropping. Foot landing ahead of the body.",STOP,"Repeated wall switches; two-point acceleration","Wall march","A-skip; falling-start acceleration"),
    E("a_skip","A-Skip","speed_drill","upright_sprint_preparation","maximum_velocity","mobility_preparation;reactive_elastic_strength","preparation","hip_flexors;calves;glutes","","field;track;court","intermediate",(3,2,2),"no",SPEED_DOSE,"Skip forward with a rhythmic thigh lift and active downward foot strike beneath the body.","Tall posture. Step over and down. Rhythm before speed.","Reaching forward. Excessive backside action. Forcing height or speed without rhythm.",SPEED_STOP,"Faster rhythm; supervised wicket run","A-march; marching drill","power skipping; progressive build-up run"),
    E("falling_start_acceleration","Falling-Start Acceleration","speed_drill","linear_acceleration","acceleration","horizontal_power;explosive_strength","primary","glutes;quadriceps;hamstrings;calves","","field;track;court","beginner",(2,2,3),"no",SPEED_DOSE,"Stand tall, lean forward as one unit until balance is lost, then project into a short acceleration without a false step.","Fall as one piece. Push back. Accelerate through the line.","Bending at the hips. Stepping backward first. Standing upright immediately.",SPEED_STOP,"Two-point-start acceleration; longer acceleration distance","Wall march; shorter distance","rolling or split-stance start"),
    E("two_point_start_acceleration","Two-Point-Start Acceleration","speed_drill","linear_acceleration","acceleration","horizontal_power;explosive_strength","primary","glutes;quadriceps;hamstrings;calves","","field;track;court","intermediate",(3,2,3),"no",SPEED_DOSE,"Use a staggered standing stance and accelerate through the prescribed distance with strong backward force and progressive rise.","Push, do not reach. Project forward. Rise gradually.","Rocking before the start. Overstriding. Popping upright in the first steps.",SPEED_STOP,"Three-point start; light sled acceleration; longer distance","Falling start; shorter distance","split-stance or rolling start"),
    E("three_point_start_acceleration","Three-Point-Start Acceleration","speed_drill","linear_acceleration","acceleration","horizontal_power;explosive_strength","primary","glutes;quadriceps;hamstrings;calves","track_or_safe_surface","field;track","advanced",(4,2,4),"yes",SPEED_DOSE,"Set a stable three-point stance and accelerate through the prescribed distance while maintaining projection and progressive rise.","Stable set. Push through the ground. Patient rise.","Unstable hand position. First step reaching. Rushing upright mechanics.",SPEED_STOP,"Block start with qualified coaching; longer acceleration","Two-point start","falling start; light sled acceleration"),
    E("light_sled_acceleration","Light Resisted Sled Acceleration","speed_drill","resisted_linear_acceleration","acceleration","horizontal_power;explosive_strength","primary","glutes;quadriceps;hamstrings;calves","sled;harness;plates","field;track","intermediate",(3,2,4),"yes",SPEED_DOSE + ";sled_load","Attach a securely loaded sled and accelerate while preserving the intended acceleration pattern and prescribed velocity loss.","Push back. Keep rhythm. Resistance must not turn the run into a grind.","Excessive load. Shuffling steps. Rounded posture. Loose harness or unsafe lane.",SPEED_STOP + " Reduce resistance when acceleration mechanics or velocity fall outside the prescribed range.","Slightly greater reviewed resistance or distance","Lighter sled; unresisted two-point start","hill acceleration; unresisted acceleration"),
    E("progressive_build_up_run","Progressive Build-Up Run","speed_drill","upright_sprint_transition","maximum_velocity","acceleration;mobility_preparation","preparation","hamstrings;glutes;calves","","field;track","beginner",(2,2,2),"no",SPEED_DOSE,"Increase speed smoothly across the prescribed build distance, reaching the target without straining or abrupt acceleration.","Smooth rise. Tall and relaxed. Finish fast, not forced.","Starting too fast. Tensing shoulders. Sprinting beyond the safe target.",SPEED_STOP,"Longer build or flying sprint exposure","Shorter/slower build","progressive stride"),
    E("flying_sprint","Flying Sprint","speed_drill","maximum_velocity_sprinting","maximum_velocity","reactive_elastic_strength;speed_endurance","primary","hamstrings;glutes;calves","cones;timing_gates_optional","field;track","intermediate",(4,3,4),"yes",SPEED_DOSE + ";build_distance_m;fly_distance_m","Build speed progressively, then maintain relaxed upright sprinting through the short flying zone before controlled deceleration.","Build, rise, fly. Tall hips. Fast and relaxed.","Inadequate build-up. Straining through the fly zone. Abrupt stopping after the line.",SPEED_STOP,"Longer fly zone or faster verified exposure","Build-up runs without fly zone","wicket run; short maximum-velocity exposure"),
    E("wicket_run","Supervised Wicket Run","speed_drill","upright_sprint_rhythm","maximum_velocity","reactive_elastic_strength;mobility_preparation","primary","hamstrings;glutes;calves","wickets_or_mini_hurdles;measuring_tape","track;field","advanced",(5,3,4),"yes",SPEED_DOSE + ";wicket_spacing_m","Run through individually reviewed wicket spacing after a progressive build, maintaining rhythm without reaching for barriers.","Step over and down. Stay tall. Let spacing guide rhythm.","Using generic spacing. Reaching forward. Raising barriers. Continuing after rhythm breaks.",SPEED_STOP + " Wicket spacing and height require qualified setup; never guess spacing from body height alone.","Individually adjusted spacing or faster approach","A-skip; build-up run","flying sprint"),
    E("short_speed_endurance_run","Short Speed-Endurance Run","conditioning_modality","high_speed_running","speed_endurance","anaerobic_capacity;maximum_velocity","primary","whole_body","cones;timing_gates_optional","field;track","intermediate",(4,3,5),"yes",COND_DOSE,"Run the prescribed high-speed distance with long recovery so each repetition remains a speed-quality effort rather than generic conditioning.","Fast and composed. Preserve mechanics. Recover fully.","Short recovery. Excessive repetitions. Treating declining runs as toughness work.",SPEED_STOP,"Longer distance or one additional quality repetition","Shorter distance; fewer repetitions","cycling sprint repeat when impact must be reduced"),
    E("long_sprint_endurance_run","Long Sprint-Endurance Run","conditioning_modality","long_sprint_running","speed_endurance","anaerobic_capacity;anaerobic_power","primary","whole_body","cones;timing_gates_optional","track;field","advanced",(5,4,5),"yes",COND_DOSE,"Complete the prescribed long sprint at high controlled intensity with extensive recovery and stop before mechanics become unsafe.","Commit to the target. Relax under fatigue. Full recovery.","Racing every repetition. Insufficient rest. Adding volume after severe output loss.",SPEED_STOP,"Event-specific longer exposure only within reviewed sprint package","Short speed-endurance run; fewer reps","bike anaerobic-capacity interval"),
    E("planned_linear_stop","Planned Linear Stop","deceleration_drill","linear_deceleration","deceleration","landing_capacity;eccentric_capacity","primary","quadriceps;glutes;calves","cones","field;court;gym","beginner",(2,2,2),"no",COD_DOSE,"Approach at the prescribed speed, lower the centre of mass and stop under control inside a generous marked zone.","Lower before the line. Use several braking steps. Finish balanced.","Stopping in one rigid step. Upright braking. Crossing feet or falling backward.",STOP,"Progressive-speed deceleration; shorter stopping zone","Lower approach speed; longer stopping zone","backward sled drag for lower-impact force absorption"),
    E("progressive_speed_deceleration","Progressive-Speed Deceleration","deceleration_drill","linear_deceleration","deceleration","eccentric_capacity;change_of_direction","primary","quadriceps;glutes;calves","cones","field;court","intermediate",(3,3,3),"no",COD_DOSE,"Increase approach speed gradually across repetitions while stopping inside the prescribed zone with stable posture.","Speed rises only when the stop stays clean. Lower early. Own the finish.","Increasing speed and shortening zone together. Late braking. Continuing after control is lost.",STOP,"Shorter zone; lateral stop; planned cut","Slower approach; longer zone","planned linear stop"),
    E("lateral_stop","Lateral Stop","deceleration_drill","lateral_deceleration","deceleration","lateral_power;adductor_capacity","primary","glutes;adductors;quadriceps","cones","field;court;gym","intermediate",(3,3,3),"no",COD_DOSE,"Move laterally at the prescribed speed and use controlled steps to stop with the trunk and pelvis balanced over the base.","Sink into the hip. Foot under control. Finish square and balanced.","Foot planted too far outside. Knee collapse. Trunk falling away from the stop.",STOP,"Lateral redirection or 90-degree cut","Slower shuffle and wider stop zone","planned linear stop"),
    E("planned_45_degree_cut","Planned 45-Degree Cut","change_of_direction_drill","shallow_angle_change_of_direction","change_of_direction","deceleration;acceleration","primary","glutes;quadriceps;adductors;calves","cones","field;court","beginner",(3,3,3),"no",COD_DOSE,"Approach a known marker, lower under control and redirect approximately 45 degrees before reaccelerating.","Brake before the cut. Plant under control. Push into the new line.","Cutting upright. Reaching the plant too far. Adding speed before control.",STOP,"Faster approach; 90-degree cut","Slower approach; walk-through","curved run redirection"),
    E("planned_90_degree_cut","Planned 90-Degree Cut","change_of_direction_drill","right_angle_change_of_direction","change_of_direction","deceleration;lateral_power","primary","glutes;quadriceps;adductors;calves","cones","field;court","intermediate",(4,3,4),"no",COD_DOSE,"Approach a known marker, decelerate before the plant and redirect approximately 90 degrees with controlled trunk and foot position.","Brake first. Control the plant. Reaccelerate out.","Late braking. Excessively wide plant. Knee collapse or uncontrolled trunk lean.",STOP,"Higher approach speed; multidirectional sequence","45-degree cut; slower approach","lateral stop plus acceleration"),
    E("planned_180_degree_turn","Planned 180-Degree Turn","change_of_direction_drill","reversal_change_of_direction","change_of_direction","deceleration;acceleration","primary","glutes;quadriceps;adductors;calves","cones","field;court","advanced",(4,4,4),"yes",COD_DOSE,"Approach the line, reduce speed, execute a reviewed 180-degree turn strategy and reaccelerate along the original path.","Arrive under control. Turn compactly. Drive out.","Overrunning the line. Upright turn. Twisting on a fixed foot without control.",STOP,"Faster approach or repeated reversal","90-degree cut; lower-speed shuttle turn","curved reversal pattern"),
    E("planned_multidirectional_sequence","Planned Multidirectional Sequence","change_of_direction_drill","multidirectional_change_of_direction","change_of_direction","deceleration;acceleration;lateral_power","primary","whole_body","cones","field;court","advanced",(5,4,5),"yes",COD_DOSE,"Complete a pre-planned sequence of two or more direction changes while preserving braking quality at every cut.","Know the route. Win each brake. Accelerate between cuts.","Turning it into conditioning. Too many cuts. Losing technique after the first direction.",STOP,"Higher speed or later reactive overlay","Single 45- or 90-degree cut","shorter planned sequence"),
    E("single_cue_reactive_cut","Single-Cue Reactive Cut","reactive_agility_drill","single_choice_reactive_change","reactive_agility","change_of_direction;perceptual_response","primary","whole_body","cones;visual_or_audio_cue","field;court","beginner",(3,3,3),"yes",COD_DOSE + ";stimulus_type","Respond to one clearly defined external cue by selecting between a small number of previously practiced movement options.","See the cue, brake, then act. Quality before speed.","Guessing before the cue. Too many choices. Using reactive work before planned control.",STOP,"More choices or higher approach speed","Planned cut with coach call before movement","single-direction chase"),
    E("multi_choice_reactive_cut","Multi-Choice Reactive Cut","reactive_agility_drill","multi_choice_reactive_change","reactive_agility","change_of_direction;perceptual_response","primary","whole_body","cones;visual_or_audio_cue","field;court","advanced",(5,4,5),"yes",COD_DOSE + ";stimulus_type;choice_count","React to an unpredictable external cue selecting among multiple previously competent movement solutions.","Read first. Control the brake. Choose and go.","Artificially complex cues. Excessive duration. Technique collapse under uncertainty.",STOP,"More sport-relevant information or partner task","Single-cue reactive cut","partner mirror drill"),
    E("partner_mirror_drill","Partner Mirror Drill","reactive_agility_drill","partner_reactive_lateral_movement","reactive_agility","deceleration;lateral_power","primary","whole_body","partner;marked_area","field;court;gym","intermediate",(4,3,4),"yes",COD_DOSE + ";bout_duration_seconds","One athlete leads inside a bounded area while the other mirrors for a short timed bout; switch roles after full recovery.","Watch the hips. Stay balanced. Short quality bouts.","Area too large. Bouts becoming conditioning. Contact or unsafe deception.",STOP,"Faster leader or multidirectional area","Single-cue lateral response","partner chase drill"),
    E("partner_chase_drill","Partner Chase Drill","reactive_agility_drill","partner_reactive_chase","reactive_agility","acceleration;change_of_direction","primary","whole_body","partner;marked_area","field;court","advanced",(5,4,5),"yes",COD_DOSE + ";bout_duration_seconds","A leader initiates within a bounded area and the chaser responds, using a short non-contact chase with a clear stop boundary.","React, accelerate, stay under control. End at the boundary.","Contact. Long fatigue bouts. Unsafe closing speed or poor space.",STOP,"More representative but still bounded task","Partner mirror; single-cue reactive cut","multi-choice reactive cut"),
    E("split_squat_yielding_hold","Split-Squat Yielding Hold","isometric","split_squat_isometric","isometric_force_capacity","adductor_capacity;trunk_force_transfer","capacity","quadriceps;glutes;adductors","dumbbells_optional","gym;home;field","beginner",(2,1,3),"no",ISO_DOSE,"Hold a stable split-squat position at the prescribed joint depth while maintaining even foot pressure and trunk control.","Own the position. Front foot flat. Breathe behind the brace.","Drifting forward. Back knee collapsing inward. Holding breath or changing depth.",STOP,"Longer hold; external load; lower joint angle","Higher position; assisted hold","Spanish squat hold"),
    E("standing_calf_raise_hold","Standing Calf-Raise Hold","isometric","straight_knee_plantar_flexion_isometric","calf_soleus_capacity","isometric_force_capacity","capacity","gastrocnemius;soleus","wall_support_optional;dumbbells_optional","gym;home;field","beginner",(2,1,2),"no",ISO_DOSE,"Rise onto the forefoot with the knee straight and hold the prescribed height without rolling to the outside of the foot.","Stay tall. Big toe pressure. Hold the same height.","Ankle rolling out. Heel dropping. Using painful end range.",STOP,"Single-leg or loaded hold","Bilateral supported hold at lower height","standing calf raise"),
    E("bent_knee_soleus_hold","Bent-Knee Soleus Hold","isometric","bent_knee_plantar_flexion_isometric","calf_soleus_capacity","isometric_force_capacity","capacity","soleus;calves","wall_support_optional;dumbbells_optional","gym;home;field","beginner",(2,1,2),"no",ISO_DOSE,"Maintain a bent-knee stance, raise the heel and hold with the knee position and heel height unchanged.","Knee stays bent. Heel stays high. Pressure through the forefoot.","Straightening the knee. Heel drifting down. Foot rolling outward.",STOP,"Single-leg or externally loaded hold","Bilateral supported hold","seated calf raise"),
    E("hamstring_bridge_hold","Hamstring Bridge Hold","isometric","hip_extension_knee_flexion_isometric","hamstring_capacity","isometric_force_capacity;trunk_force_transfer","capacity","hamstrings;glutes","mat","gym;home;field","beginner",(2,1,3),"no",ISO_DOSE,"Place heels at the prescribed distance, lift the hips and hold without arching the back or losing heel pressure.","Dig heels down. Hips level. Ribs controlled.","Cramping from excessive effort. Back arching. Hips dropping or feet slipping.",STOP,"Longer lever; single-leg hold; external load","Shorter lever; glute bridge hold","slider hamstring curl"),
    E("overcoming_mid_thigh_pull","Overcoming Mid-Thigh Pull","isometric","hinge_overcoming_isometric","isometric_force_capacity","maximum_strength;explosive_strength","primary","glutes;quadriceps;hamstrings;trunk","immovable_bar;power_rack;straps_optional","gym","intermediate",(5,1,4),"yes",ISO_DOSE,"Set a securely fixed bar at the reviewed mid-thigh position, brace, ramp force and pull maximally against the immovable setup for the prescribed duration.","Set position first. Ramp hard. Push the floor and pull the bar.","Unsafe rack setup. Jerking before bracing. Changing joint position during the effort.",STOP + " Requires a verified immovable setup, clear rack instructions and competent supervision.","Higher verified force intent or rapid-intent variant","Submaximal yielding hinge hold","trap-bar deadlift"),
    E("overcoming_split_squat_push","Overcoming Split-Squat Push","isometric","split_squat_overcoming_isometric","isometric_force_capacity","maximum_strength;acceleration","primary","quadriceps;glutes;adductors","immovable_bar;power_rack","gym","intermediate",(5,1,4),"yes",ISO_DOSE,"Assume a reviewed split stance beneath an immovable bar or support and push maximally without changing position.","Stable feet. Brace first. Push hard without rising.","Insecure setup. Painful joint angle. Shifting stance or twisting under effort.",STOP + " Requires a secure immovable setup and reviewed joint position.","Rapid-intent effort or alternate reviewed angle","Yielding split-squat hold","split squat strength exercise"),
]


def modality(code, name, pattern, quality, secondary, equipment, env, level, costs,
             instructions, cues, mistakes, safety, progressions, regressions, substitutions):
    return E(code, name, "conditioning_modality", pattern, quality, secondary, "primary",
             "cardiorespiratory_system;whole_body", equipment, env, level, costs, "no",
             COND_DOSE, instructions, cues, mistakes, safety, progressions, regressions,
             substitutions)


ENTRIES += [
    modality("run_walk_intervals","Run-Walk Intervals","intermittent_running","aerobic_capacity","recovery_capacity","timer;safe_route","road;track;field;treadmill","beginner",(1,2,2),"Alternate prescribed easy running and walking bouts, keeping effort conversational and finishing before form deteriorates.","Easy means easy. Walk early, not after failure. Keep the same safe route.","Running bouts too hard. Removing walk recoveries prematurely. Increasing duration and speed together.",COND_STOP,"Longer run bouts or total duration","Shorter run bouts; longer walks","easy cycling or pool aerobic intervals"),
    modality("easy_continuous_run","Easy Continuous Run","continuous_running","aerobic_capacity","recovery_capacity","safe_route_or_treadmill","road;track;field;treadmill","beginner",(1,2,2),"Run continuously at an easy talk-test or prescribed low-intensity zone on a safe route.","Relaxed rhythm. Full sentences. Finish with reserve.","Moderate-hard drift. Chasing pace in heat or hills. Extending duration despite pain.",COND_STOP,"Increase duration gradually or add a separate quality session","Run-walk intervals; shorter duration","easy cycling or swimming"),
    modality("long_aerobic_run","Long Aerobic Run","long_continuous_running","aerobic_capacity","local_muscular_endurance;recovery_capacity","safe_route;hydration_as_needed","road;track;trail_supported","intermediate",(2,3,4),"Run at a controlled easy intensity for the prescribed duration, using an established history-based long-run progression.","Start easier than expected. Fuel and hydrate to plan. Keep late pace controlled.","Large duration jump. Turning the finish into a race. Ignoring heat, terrain or fueling needs.",COND_STOP + " Long duration requires prior training history and environmental planning.","Small duration increase within history-based limit","Shorter easy run; split duration","long easy cycle or swim"),
    modality("steady_tempo_run","Steady/Tempo Run","continuous_moderate_running","threshold_capacity","aerobic_capacity","safe_route_or_treadmill","road;track;treadmill","beginner",(2,2,3),"Run continuously at a controlled steady intensity below all-out effort, using the prescribed RPE or validated pace anchor.","Controlled pressure. Even effort. Stop before racing.","Starting at threshold or faster. Pace chasing on hills. Unplanned progression to exhaustion.",COND_STOP,"Longer steady duration or threshold intervals","Easy continuous run; shorter tempo","steady cycling"),
    modality("threshold_run_intervals","Threshold Running Intervals","running_intervals","threshold_capacity","aerobic_capacity","timer;safe_route_or_track","road;track;treadmill","intermediate",(2,3,4),"Complete controlled work intervals near the validated threshold anchor with prescribed easy recoveries and stable output.","Settle early. Repeat, do not race. Keep the final interval comparable.","Using guessed pace as exact truth. First repetition too fast. Shortening recovery to increase difficulty.",COND_STOP,"Longer intervals or more total work, one variable at a time","Shorter intervals; steady tempo","cycling threshold intervals"),
    modality("long_aerobic_power_intervals","Long Aerobic-Power Intervals","long_high_intensity_intervals","high_intensity_aerobic_power","aerobic_capacity","timer;mode_specific_equipment","field;track;road;treadmill;gym","intermediate",(2,3,4),"Perform 2–5 minute high-aerobic intervals at the prescribed mode-specific anchor with sufficient recovery to keep output inside range.","Hard but repeatable. Match the target. Protect the final interval.","All-out first repetition. Unregistered intensity anchor. Continuing through excessive output loss.",COND_STOP,"Add one interval or modest work duration","Shorter aerobic-power intervals; threshold work","cycling or swimming aerobic-power intervals"),
    modality("short_aerobic_power_intervals","Short Aerobic-Power Intervals","short_high_intensity_intervals","high_intensity_aerobic_power","aerobic_capacity","timer;mode_specific_equipment","field;track;road;treadmill;gym","beginner",(2,2,3),"Repeat short hard bouts with prescribed recovery, accumulating high-aerobic work without turning every effort into a maximal sprint.","Hard and repeatable. Stay on the clock. Preserve movement quality.","Confusing with sprint training. Too little recovery. Adding repetitions after form or output fails.",COND_STOP,"More repetitions or slightly longer work","Fewer/shorter bouts; threshold intervals","bike, rower or pool intervals"),
    modality("shuttle_aerobic_power_intervals","Shuttle Aerobic-Power Intervals","shuttle_running_intervals","high_intensity_aerobic_power","change_of_direction;repeated_high_intensity_ability","cones;timer","field;court","intermediate",(3,3,4),"Run prescribed shuttle bouts at controlled high-aerobic effort, using known turn technique and enough recovery to maintain the target.","Control the turns. Even work bouts. Conditioning, not max sprinting.","Too-sharp turns for level. Racing early. Ignoring accumulated COD load.",COND_STOP + " Count direction-change load and do not use when braking competence or surface safety is inadequate.","Longer bouts or more repetitions","Linear intervals; fewer turns","bike aerobic-power intervals"),
    modality("maximal_short_sprint_repeats","Maximal Short Sprint Repeats","maximal_short_efforts","anaerobic_power","acceleration;speed_endurance","timer;safe_lane","track;field;court;cycle_ergometer","intermediate",(4,3,4),"Perform very short maximal or near-maximal efforts with long recovery, ending the set before meaningful output decline.","Explode, then recover fully. Every repetition is quality.","Short recovery. Excess volume. Confusing power with fatigue tolerance.",COND_STOP,"One additional repeat or method-specific duration increase","Fewer repeats; submaximal acceleration","cycling sprint repeats"),
    modality("anaerobic_capacity_intervals","Anaerobic-Capacity Intervals","severe_short_intervals","anaerobic_capacity","anaerobic_power","timer;mode_specific_equipment","track;field;gym;pool","beginner",(3,3,5),"Complete severe but bounded intervals with the prescribed work-to-recovery ratio, stopping when output loss exceeds the template limit.","Hard, controlled start. Respect recovery. Finish within the output boundary.","All-out pacing when not prescribed. Adding rounds after severe decline. Mixing with another hard conditioning block.",COND_STOP,"More work or shorter recovery, never both together","Shorter work; longer recovery; fewer intervals","bike or pool anaerobic-capacity intervals"),
    modality("linear_repeated_sprints","Linear Repeated-Sprint Protocol","repeated_linear_sprinting","repeated_sprint_ability","anaerobic_power;speed_endurance","cones;timer","field;track;court","beginner",(3,3,5),"Complete short linear sprints separated by incomplete but prescribed recovery, with full set recovery and a defined output-loss limit.","Fast repeats, controlled set. Hit the line. Stop at the loss limit.","Starting without sprint competence. No output criterion. Turning every conditioning session into RSA.",COND_STOP,"More repetitions or a second set","Longer recovery; fewer sprints","cycling sprint repeats"),
    modality("cod_repeated_sprints","COD Repeated-Sprint Protocol","repeated_change_of_direction_sprinting","repeated_sprint_ability","change_of_direction;deceleration","cones;timer","field;court","intermediate",(4,4,5),"Repeat short sprints containing a previously competent planned turn, using prescribed incomplete recovery and full set recovery.","Sprint, control the turn, reaccelerate. Keep every cut recognizable.","Using unfamiliar cuts. Excessive angles or distance. Ignoring COD and sprint load together.",COND_STOP + " Requires planned COD competence and a safe surface.","Additional repeat or more representative angle","Linear repeated sprints; fewer turns","shuttle aerobic-power intervals"),
    modality("repeated_high_intensity_cluster","Repeated High-Intensity Cluster","mixed_repeated_high_intensity","repeated_high_intensity_ability","anaerobic_capacity;local_muscular_endurance","cones;medicine_ball_optional;sled_optional","field;court;gym","beginner",(4,3,5),"Repeat a fixed nontechnical cluster of approved locomotor or loaded efforts with defined work, transition, recovery and output criteria.","Same actions every round. Smooth transitions. Stop before technique unravels.","Random circuits. Adding sport skills. Too many exercises or unbounded fatigue.",COND_STOP,"Additional round or slightly denser work","Fewer actions; longer recovery","linear repeated-sprint protocol; sled intervals"),
    modality("easy_continuous_cycle","Easy Continuous Cycling","continuous_cycling","aerobic_capacity","recovery_capacity","bicycle_or_cycle_ergometer","road;gym;home","beginner",(1,1,2),"Cycle continuously at easy talk-test or prescribed low-intensity power/heart-rate range with comfortable cadence.","Easy pressure. Smooth cadence. Finish fresher than hard work.","Grinding a heavy gear. Intensity drift. Unsafe road conditions.",COND_STOP,"Longer duration","Shorter duration or lower resistance","easy run, row or swim"),
    modality("cycling_threshold_intervals","Cycling Threshold Intervals","cycling_intervals","threshold_capacity","aerobic_capacity","bicycle_or_cycle_ergometer;power_meter_optional","road;gym;home","intermediate",(2,1,4),"Complete controlled cycling intervals near the validated threshold anchor with prescribed easy spinning recovery.","Even power. Sustainable cadence. Repeat, do not time-trial the first interval.","Using FTP estimate without validation. Power spikes. Recovery resistance too high.",COND_STOP,"Longer intervals or more total work","Shorter intervals; steady cycling","threshold running or swimming intervals"),
    modality("cycling_aerobic_power_intervals","Cycling Aerobic-Power Intervals","high_intensity_cycling_intervals","high_intensity_aerobic_power","aerobic_capacity","cycle_ergometer_or_bicycle;power_meter_optional","road;gym;home","intermediate",(2,1,4),"Perform high-aerobic cycling intervals at the prescribed power, heart-rate or RPE anchor with controlled cadence and recovery.","Hard and repeatable. Hold cadence. Keep output inside range.","All-out first bout. Low-cadence grinding unless prescribed. Continuing after excessive power loss.",COND_STOP,"Add interval or work duration","Threshold cycling; fewer intervals","rowing or swimming aerobic-power intervals"),
    modality("cycling_sprint_repeats","Cycling Sprint Repeats","maximal_cycling_sprints","anaerobic_power","anaerobic_capacity","cycle_ergometer_or_bicycle","road;track;gym;home","beginner",(3,1,4),"Perform very short maximal or near-maximal cycling efforts with long recovery and a consistent starting protocol.","Explode, spin through, recover fully. Repeat the same setup.","Unsafe outdoor sprinting. Inconsistent resistance. Short rest or excessive repetitions.",COND_STOP,"Additional repeat or reviewed resistance change","Submaximal short efforts; fewer reps","maximal short run or swim repeats"),
    modality("swimming_threshold_intervals","Swimming Threshold Intervals","swimming_intervals","threshold_capacity","aerobic_capacity","pool;pace_clock","pool","intermediate",(3,1,4),"Swim repeated distances at a controlled threshold-related pace with specified stroke, pool length, send-off and rest.","Even splits. Hold stroke quality. Know the send-off.","Missing pool length or stroke. Racing early repeats. Rest too short to preserve form.",COND_STOP + " Stop for distress in water and follow pool supervision rules.","More distance or repetitions","Shorter repeats; aerobic swim","cycling threshold intervals"),
    modality("swimming_sprint_repeats","Swimming Sprint Repeats","maximal_swimming_sprints","anaerobic_power","upper_body_power;anaerobic_capacity","pool;pace_clock","pool","intermediate",(4,2,4),"Swim short maximal or near-maximal repetitions with complete recovery and a specified stroke/start condition.","Explosive but clean. Hold water. Recover fully.","Too many repetitions. Unsafe starts. Stroke collapse or shoulder pain.",COND_STOP + " Requires appropriate water safety and supervision.","Additional repeat or reviewed start","Submaximal short repeats","cycling sprint repeats"),
    modality("swimming_anaerobic_capacity_set","Swimming Anaerobic-Capacity Set","severe_swimming_intervals","anaerobic_capacity","anaerobic_power;shoulder_capacity","pool;pace_clock","pool","intermediate",(4,2,5),"Complete severe swimming repetitions with defined distance, stroke, send-off, recovery and acceptable pace loss.","Controlled first repeat. Hold stroke. Respect the pace-loss limit.","Unspecified rest. Racing the opening rep. Continuing with severe stroke breakdown.",COND_STOP + " Account for total shoulder and swim volume.","More repetitions or distance, one change at a time","Shorter repeats; longer rest","bike anaerobic-capacity intervals"),
]


ENTRIES += [
    E("very_easy_active_cooldown","Very Easy Active Cooldown","recovery_modality","post_session_easy_movement","recovery_capacity","mobility_preparation","recovery","whole_body","mode_specific","field;gym;home;road;track;court;pool","beginner",(1,1,1),"no",REC_DOSE,"After the source session, perform very easy walking or mode-specific movement for the prescribed short duration, then finish normally.","Very easy. Comfortable breathing. This is transition, not extra training.","Claiming it clears lactate for next-day recovery. Extending duration. Continuing despite dizziness or heat illness signs.",STOP,"No progression required; retain only if useful","Shorter cooldown or none","passive rest"),
    E("low_impact_recovery_session","Low-Impact Recovery Session","recovery_modality","low_impact_easy_movement","recovery_capacity","aerobic_capacity","recovery","whole_body","cycle_ergometer;pool;rower_optional","gym;home;pool","beginner",(1,1,1),"no",REC_DOSE,"Perform easy low-impact movement for a short prescribed duration only when it leaves the athlete feeling the same or better.","Easy enough to recover. No pace target. Stop if it becomes work.","Turning it into conditioning. Adding it during congestion. Using a painful modality.",STOP,"No intensity progression; duration only if still restorative","Shorter session or passive rest","easy walk; easy swim; easy cycle"),
    E("optional_foam_rolling","Optional Symptom-Free Foam Rolling","recovery_modality","self_massage","mobility_range_capacity","recovery_capacity","recovery","selected_soft_tissue_region","foam_roller","gym;home;field","beginner",(1,1,1),"no","regions;duration_seconds;pressure_rpe","Roll one approved region slowly for the prescribed time at comfortable pressure, avoiding joints, acute injury and neurological symptoms.","Comfortable pressure. Slow passes. Stop before pain or numbness.","Aggressive painful pressure. Rolling acute injury. Claiming to break adhesions or permanently change fascia.",STOP + " Do not roll areas with acute trauma, unexplained swelling, vascular concern or altered sensation without professional clearance.","No required progression; retain only for confirmed comfort or acute ROM response","Less pressure/time or omit","gentle mobility; passive rest"),
    E("passive_rest","Passive Rest / No Modality","recovery_modality","rest","recovery_capacity","","recovery","whole_body","","home;field;gym;travel","beginner",(1,1,1),"no","duration_seconds","Do not add a recovery exercise or modality. Protect ordinary rest, sleep opportunity, nutrition, hydration and the next-session schedule.","Nothing extra is required. Recover through time and appropriate load management.","Treating rest as failure. Stacking optional modalities without a defined outcome. Replacing medical care with rest.",STOP,"Resume planned training when readiness and schedule gates pass","Additional rest or professional review when indicated","very easy cooldown or low-impact recovery only for a defined purpose"),
]


def main():
    with CSV_PATH.open(encoding="utf-8-sig", newline="") as fh:
        existing = list(csv.DictReader(fh))
    existing = [row for row in existing if not row["source_id"].startswith("EXT-")]
    existing_codes = {row["code"] for row in existing}
    new_codes = [row["code"] for row in ENTRIES]
    if len(ENTRIES) != 58 or len(new_codes) != len(set(new_codes)):
        raise SystemExit(f"Expected 58 unique entries, found {len(ENTRIES)} rows/{len(set(new_codes))} codes")
    overlap = existing_codes & set(new_codes)
    if overlap:
        raise SystemExit(f"Extension codes already exist: {sorted(overlap)}")
    output = existing[:]
    for index, item in enumerate(ENTRIES, 1):
        row = {field: "" for field in FIELDS}
        row.update(item)
        row.update({
            "source_id": f"EXT-{index:03d}",
            "catalogue_scope": "template_required_extension",
            "generator_eligible": "no",
            "approval_status": "pending_review",
            "approved_by": "",
            "approval_scope": "Research-derived candidate; requires content, safety and taxonomy review before generator release",
        })
        output.append(row)
    with CSV_PATH.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=FIELDS, extrasaction="raise")
        writer.writeheader()
        writer.writerows(output)
    print(f"Wrote {len(output)} rows: {len(existing)} existing + {len(ENTRIES)} extensions")


if __name__ == "__main__":
    main()
