import React, { useEffect, useState } from 'react';
import { ScrollView, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { CoachBottom, CoachCard, CoachChip, CoachField, CoachProgress, CoachSection, coachLayout } from '../../src/components/onboarding/CoachOnboarding';
import { useOnboardingStore } from '../../src/store/onboardingStore'; import { useAuthStore } from '../../src/store/authStore';
const GENDERS=[['female','Female'],['male','Male'],['non_binary','Non-binary'],['prefer_not_to_say','Prefer not to say']];
export default function ProfileScreen(){const router=useRouter();const insets=useSafeAreaInsets();const store=useOnboardingStore();const {user}=useAuthStore();const [gender,setGender]=useState(store.gender);const [height,setHeight]=useState(store.height_cm);const [weight,setWeight]=useState(store.weight_kg);const [target,setTarget]=useState(store.target_weight_kg);
 useEffect(()=>{if(!store.date_of_birth&&user?.birth_date)store.setBodyProfile({date_of_birth:user.birth_date})},[store,user]);
 const next=()=>{store.setBodyProfile({gender,height_cm:height,weight_kg:weight,target_weight_kg:target});router.push('/onboarding/schedule')};
 return <View style={[coachLayout.container,{paddingTop:insets.top}]}><CoachProgress step={4}/><ScrollView style={coachLayout.scrollView} contentContainerStyle={coachLayout.content}><CoachCard icon="person" eyebrow="BODY CONTEXT" title="Tell us the basics." subtitle="These details help the coach estimate load, recovery, and fueling needs."><CoachSection title="Gender"/><View style={coachLayout.chipGrid}>{GENDERS.map(([id,label])=><CoachChip key={id} label={label} selected={gender===id} onPress={()=>setGender(id)}/>)}</View><CoachSection title="Stats" meta="Optional"/><View style={coachLayout.fieldGrid}><CoachField style={coachLayout.halfField} label="Height" value={height} onChangeText={setHeight} placeholder="cm" keyboardType="decimal-pad"/><CoachField style={coachLayout.halfField} label="Weight" value={weight} onChangeText={setWeight} placeholder="kg" keyboardType="decimal-pad"/><CoachField style={coachLayout.halfField} label="Target weight" value={target} onChangeText={setTarget} placeholder="kg" keyboardType="decimal-pad"/></View></CoachCard></ScrollView><CoachBottom bottomInset={insets.bottom} onPress={next}/></View>}
