import React, { useState } from 'react';
import { ScrollView, View } from 'react-native'; import { useRouter } from 'expo-router'; import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { CoachBottom, CoachCard, CoachChip, CoachField, CoachNote, CoachProgress, CoachSection, coachLayout } from '../../src/components/onboarding/CoachOnboarding';
import { DayAvailability, useOnboardingStore } from '../../src/store/onboardingStore';
const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']; const TIMES=[45,60,75,90,120,150];
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export default function ScheduleScreen(){const router=useRouter();const insets=useSafeAreaInsets();const store=useOnboardingStore();const [slots,setSlots]=useState<DayAvailability[]>(store.availability);const [start,setStart]=useState(store.start_date||iso(new Date()));const [notes,setNotes]=useState(store.schedule_constraints);
 const toggle=(day:string)=>setSlots(x=>x.some(s=>s.day===day)?x.filter(s=>s.day!==day):[...x,{day,minutes:day==='Sat'||day==='Sun'?120:60,preferredTime:'morning'}]);
 const update=(day:string,change:Partial<DayAvailability>)=>setSlots(x=>x.map(s=>s.day===day?{...s,...change}:s));
 const next=()=>{store.setSchedule({availability:slots,start_date:start,schedule_constraints:notes});router.push('/onboarding/equipment')};
 return <View style={[coachLayout.container,{paddingTop:insets.top}]}><CoachProgress step={5}/><ScrollView style={coachLayout.scrollView} contentContainerStyle={coachLayout.content}><CoachCard icon="calendar" eyebrow="TRAINING WEEK" title="When can you train?" subtitle="Set the maximum time available on each day. Easier sessions may be shorter."><CoachSection title="Available days" meta={`${slots.length} selected`}/><View style={coachLayout.chipGrid}>{DAYS.map(d=><CoachChip key={d} label={d} selected={slots.some(s=>s.day===d)} onPress={()=>toggle(d)}/>)}</View>{DAYS.filter(d=>slots.some(s=>s.day===d)).map(day=>{const slot=slots.find(s=>s.day===day)!;return <View key={day}><CoachSection title={day} meta={`${slot.minutes} min · ${slot.preferredTime}`}/><View style={coachLayout.chipGrid}>{TIMES.map(t=><CoachChip key={t} label={`${t} min`} selected={slot.minutes===t} onPress={()=>update(day,{minutes:t})}/>)}</View><View style={coachLayout.chipGrid}>{(['morning','afternoon','evening'] as const).map(t=><CoachChip key={t} label={t} selected={slot.preferredTime===t} onPress={()=>update(day,{preferredTime:t})}/>)}</View></View>})}<CoachSection title="Plan start"/><CoachField value={start} onChangeText={setStart} placeholder="YYYY-MM-DD"/><CoachSection title="Schedule notes" meta="Optional"/><CoachField value={notes} onChangeText={setNotes} placeholder="Work shifts, travel, unavailable dates..." multiline/><CoachNote text="Hard sessions and long runs will be placed where your available time and recovery allow."/></CoachCard></ScrollView><CoachBottom bottomInset={insets.bottom} disabled={slots.length<2} onPress={next}/></View>}
